/* Generated by Yosys 0.9+4081 (git sha1 862e84eb, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

module top(a_i, b_i, op_i, r_o);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  input [7:0] a_i;
  wire [7:0] \alu_inst.a_i ;
  wire [7:0] \alu_inst.b_i ;
  wire [1:0] \alu_inst.op_i ;
  wire [15:0] \alu_inst.r_o ;
  input [7:0] b_i;
  input [1:0] op_i;
  output [15:0] r_o;
  sky130_fd_sc_hd__clkinv_1 _0523_ (
    .A(\alu_inst.b_i [0]),
    .Y(_0254_)
  );
  sky130_fd_sc_hd__clkinv_1 _0524_ (
    .A(\alu_inst.a_i [5]),
    .Y(_0264_)
  );
  sky130_fd_sc_hd__clkinv_1 _0525_ (
    .A(\alu_inst.a_i [4]),
    .Y(_0275_)
  );
  sky130_fd_sc_hd__clkinv_1 _0526_ (
    .A(\alu_inst.a_i [3]),
    .Y(_0286_)
  );
  sky130_fd_sc_hd__clkinv_1 _0527_ (
    .A(\alu_inst.a_i [2]),
    .Y(_0297_)
  );
  sky130_fd_sc_hd__clkinv_1 _0528_ (
    .A(\alu_inst.b_i [1]),
    .Y(_0308_)
  );
  sky130_fd_sc_hd__clkinv_1 _0529_ (
    .A(\alu_inst.b_i [2]),
    .Y(_0318_)
  );
  sky130_fd_sc_hd__nor2_1 _0530_ (
    .A(\alu_inst.b_i [6]),
    .B(\alu_inst.b_i [7]),
    .Y(_0329_)
  );
  sky130_fd_sc_hd__or3_1 _0531_ (
    .A(\alu_inst.b_i [6]),
    .B(\alu_inst.b_i [5]),
    .C(\alu_inst.b_i [7]),
    .X(_0340_)
  );
  sky130_fd_sc_hd__or4_1 _0532_ (
    .A(\alu_inst.b_i [4]),
    .B(\alu_inst.b_i [6]),
    .C(\alu_inst.b_i [5]),
    .D(\alu_inst.b_i [7]),
    .X(_0351_)
  );
  sky130_fd_sc_hd__nor2_1 _0533_ (
    .A(\alu_inst.b_i [3]),
    .B(_0351_),
    .Y(_0361_)
  );
  sky130_fd_sc_hd__nor3_1 _0534_ (
    .A(\alu_inst.b_i [2]),
    .B(\alu_inst.b_i [3]),
    .C(_0351_),
    .Y(_0372_)
  );
  sky130_fd_sc_hd__nor4_1 _0535_ (
    .A(\alu_inst.b_i [1]),
    .B(\alu_inst.b_i [2]),
    .C(\alu_inst.b_i [3]),
    .D(_0351_),
    .Y(_0383_)
  );
  sky130_fd_sc_hd__nand2_1 _0536_ (
    .A(\alu_inst.b_i [0]),
    .B(_0383_),
    .Y(_0393_)
  );
  sky130_fd_sc_hd__o221ai_1 _0537_ (
    .A1(_0254_),
    .A2(\alu_inst.a_i [6]),
    .B1(_0308_),
    .B2(\alu_inst.a_i [7]),
    .C1(_0372_),
    .Y(_0404_)
  );
  sky130_fd_sc_hd__and4_1 _0538_ (
    .A(_0254_),
    .B(\alu_inst.a_i [7]),
    .C(_0308_),
    .D(_0372_),
    .X(_0414_)
  );
  sky130_fd_sc_hd__a31o_1 _0539_ (
    .A1(\alu_inst.a_i [7]),
    .A2(_0393_),
    .A3(_0404_),
    .B1(_0414_),
    .X(_0425_)
  );
  sky130_fd_sc_hd__o21ai_0 _0540_ (
    .A1(_0254_),
    .A2(_0404_),
    .B1(\alu_inst.a_i [6]),
    .Y(_0435_)
  );
  sky130_fd_sc_hd__xnor2_1 _0541_ (
    .A(\alu_inst.b_i [1]),
    .B(_0435_),
    .Y(_0446_)
  );
  sky130_fd_sc_hd__nor2_1 _0542_ (
    .A(_0254_),
    .B(\alu_inst.a_i [4]),
    .Y(_0456_)
  );
  sky130_fd_sc_hd__nand2_1 _0543_ (
    .A(\alu_inst.b_i [0]),
    .B(\alu_inst.a_i [5]),
    .Y(_0467_)
  );
  sky130_fd_sc_hd__xor2_1 _0544_ (
    .A(\alu_inst.b_i [0]),
    .B(\alu_inst.a_i [5]),
    .X(_0477_)
  );
  sky130_fd_sc_hd__nor2_1 _0545_ (
    .A(_0254_),
    .B(\alu_inst.a_i [5]),
    .Y(_0480_)
  );
  sky130_fd_sc_hd__maj3_1 _0546_ (
    .A(\alu_inst.b_i [1]),
    .B(_0435_),
    .C(_0480_),
    .X(_0481_)
  );
  sky130_fd_sc_hd__nand2_1 _0547_ (
    .A(\alu_inst.b_i [2]),
    .B(_0361_),
    .Y(_0482_)
  );
  sky130_fd_sc_hd__nand2_1 _0548_ (
    .A(_0372_),
    .B(_0481_),
    .Y(_0483_)
  );
  sky130_fd_sc_hd__o211ai_1 _0549_ (
    .A1(_0481_),
    .A2(_0482_),
    .B1(_0483_),
    .C1(_0425_),
    .Y(_0484_)
  );
  sky130_fd_sc_hd__clkinv_1 _0550_ (
    .A(_0484_),
    .Y(_0485_)
  );
  sky130_fd_sc_hd__nand2_1 _0551_ (
    .A(_0318_),
    .B(_0425_),
    .Y(_0486_)
  );
  sky130_fd_sc_hd__o21ai_0 _0552_ (
    .A1(_0318_),
    .A2(_0425_),
    .B1(_0361_),
    .Y(_0487_)
  );
  sky130_fd_sc_hd__a21o_1 _0553_ (
    .A1(_0481_),
    .A2(_0486_),
    .B1(_0487_),
    .X(_0488_)
  );
  sky130_fd_sc_hd__xnor2_1 _0554_ (
    .A(_0446_),
    .B(_0480_),
    .Y(_0489_)
  );
  sky130_fd_sc_hd__mux2i_1 _0555_ (
    .A0(_0489_),
    .A1(_0435_),
    .S(_0488_),
    .Y(_0490_)
  );
  sky130_fd_sc_hd__nand2_1 _0556_ (
    .A(_0318_),
    .B(_0490_),
    .Y(_0491_)
  );
  sky130_fd_sc_hd__xnor2_1 _0557_ (
    .A(_0318_),
    .B(_0490_),
    .Y(_0492_)
  );
  sky130_fd_sc_hd__mux2i_1 _0558_ (
    .A0(_0477_),
    .A1(\alu_inst.a_i [5]),
    .S(_0488_),
    .Y(_0493_)
  );
  sky130_fd_sc_hd__xnor2_1 _0559_ (
    .A(\alu_inst.b_i [1]),
    .B(_0493_),
    .Y(_0494_)
  );
  sky130_fd_sc_hd__maj3_1 _0560_ (
    .A(\alu_inst.b_i [1]),
    .B(_0456_),
    .C(_0493_),
    .X(_0495_)
  );
  sky130_fd_sc_hd__o21a_1 _0561_ (
    .A1(_0492_),
    .A2(_0495_),
    .B1(_0491_),
    .X(_0496_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0562_ (
    .A(\alu_inst.b_i [3]),
    .SLEEP(_0351_),
    .X(_0497_)
  );
  sky130_fd_sc_hd__o21ai_0 _0563_ (
    .A1(\alu_inst.b_i [3]),
    .A2(_0351_),
    .B1(_0496_),
    .Y(_0498_)
  );
  sky130_fd_sc_hd__o21ai_0 _0564_ (
    .A1(_0496_),
    .A2(_0497_),
    .B1(_0498_),
    .Y(_0499_)
  );
  sky130_fd_sc_hd__nand2_1 _0565_ (
    .A(_0485_),
    .B(_0499_),
    .Y(_0500_)
  );
  sky130_fd_sc_hd__o221ai_1 _0566_ (
    .A1(\alu_inst.b_i [3]),
    .A2(_0484_),
    .B1(_0492_),
    .B2(_0495_),
    .C1(_0491_),
    .Y(_0501_)
  );
  sky130_fd_sc_hd__a21oi_1 _0567_ (
    .A1(\alu_inst.b_i [3]),
    .A2(_0484_),
    .B1(_0351_),
    .Y(_0502_)
  );
  sky130_fd_sc_hd__nand2_1 _0568_ (
    .A(_0501_),
    .B(_0502_),
    .Y(_0503_)
  );
  sky130_fd_sc_hd__xnor2_1 _0569_ (
    .A(_0492_),
    .B(_0495_),
    .Y(_0504_)
  );
  sky130_fd_sc_hd__a21oi_1 _0570_ (
    .A1(_0501_),
    .A2(_0502_),
    .B1(_0490_),
    .Y(_0505_)
  );
  sky130_fd_sc_hd__a31oi_1 _0571_ (
    .A1(_0501_),
    .A2(_0502_),
    .A3(_0504_),
    .B1(_0505_),
    .Y(_0506_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0572_ (
    .A(_0506_),
    .SLEEP(\alu_inst.b_i [3]),
    .X(_0507_)
  );
  sky130_fd_sc_hd__nand2b_1 _0573_ (
    .A_N(_0506_),
    .B(\alu_inst.b_i [3]),
    .Y(_0508_)
  );
  sky130_fd_sc_hd__nand2b_1 _0574_ (
    .A_N(_0507_),
    .B(_0508_),
    .Y(_0509_)
  );
  sky130_fd_sc_hd__xnor2_1 _0575_ (
    .A(_0456_),
    .B(_0494_),
    .Y(_0510_)
  );
  sky130_fd_sc_hd__mux2i_1 _0576_ (
    .A0(_0510_),
    .A1(_0493_),
    .S(_0503_),
    .Y(_0511_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0577_ (
    .A(_0318_),
    .SLEEP(_0511_),
    .X(_0512_)
  );
  sky130_fd_sc_hd__a31o_1 _0578_ (
    .A1(\alu_inst.b_i [0]),
    .A2(_0501_),
    .A3(_0502_),
    .B1(_0275_),
    .X(_0513_)
  );
  sky130_fd_sc_hd__nand3_1 _0579_ (
    .A(_0456_),
    .B(_0501_),
    .C(_0502_),
    .Y(_0514_)
  );
  sky130_fd_sc_hd__nand2_1 _0580_ (
    .A(_0513_),
    .B(_0514_),
    .Y(_0515_)
  );
  sky130_fd_sc_hd__a21oi_1 _0581_ (
    .A1(_0513_),
    .A2(_0514_),
    .B1(\alu_inst.b_i [1]),
    .Y(_0516_)
  );
  sky130_fd_sc_hd__nand2_1 _0582_ (
    .A(\alu_inst.b_i [0]),
    .B(_0286_),
    .Y(_0517_)
  );
  sky130_fd_sc_hd__nand3_1 _0583_ (
    .A(\alu_inst.b_i [1]),
    .B(_0513_),
    .C(_0514_),
    .Y(_0518_)
  );
  sky130_fd_sc_hd__nand2b_1 _0584_ (
    .A_N(_0516_),
    .B(_0518_),
    .Y(_0519_)
  );
  sky130_fd_sc_hd__a21o_1 _0585_ (
    .A1(_0517_),
    .A2(_0518_),
    .B1(_0516_),
    .X(_0520_)
  );
  sky130_fd_sc_hd__a221o_1 _0586_ (
    .A1(_0318_),
    .A2(_0511_),
    .B1(_0517_),
    .B2(_0518_),
    .C1(_0516_),
    .X(_0521_)
  );
  sky130_fd_sc_hd__nand2_1 _0587_ (
    .A(_0512_),
    .B(_0521_),
    .Y(_0522_)
  );
  sky130_fd_sc_hd__a31o_1 _0588_ (
    .A1(_0508_),
    .A2(_0512_),
    .A3(_0521_),
    .B1(_0507_),
    .X(_0000_)
  );
  sky130_fd_sc_hd__nand3b_1 _0589_ (
    .A_N(\alu_inst.b_i [5]),
    .B(_0329_),
    .C(\alu_inst.b_i [4]),
    .Y(_0001_)
  );
  sky130_fd_sc_hd__mux2i_1 _0590_ (
    .A0(_0351_),
    .A1(_0001_),
    .S(_0000_),
    .Y(_0002_)
  );
  sky130_fd_sc_hd__nor2_1 _0591_ (
    .A(_0500_),
    .B(_0002_),
    .Y(_0003_)
  );
  sky130_fd_sc_hd__nor3_1 _0592_ (
    .A(\alu_inst.b_i [5]),
    .B(_0500_),
    .C(_0002_),
    .Y(_0004_)
  );
  sky130_fd_sc_hd__nor2_1 _0593_ (
    .A(\alu_inst.b_i [4]),
    .B(_0500_),
    .Y(_0005_)
  );
  sky130_fd_sc_hd__a21oi_1 _0594_ (
    .A1(\alu_inst.b_i [4]),
    .A2(_0500_),
    .B1(_0340_),
    .Y(_0006_)
  );
  sky130_fd_sc_hd__o21ai_0 _0595_ (
    .A1(_0000_),
    .A2(_0005_),
    .B1(_0006_),
    .Y(_0007_)
  );
  sky130_fd_sc_hd__xnor2_1 _0596_ (
    .A(_0509_),
    .B(_0522_),
    .Y(_0008_)
  );
  sky130_fd_sc_hd__nor2_1 _0597_ (
    .A(_0007_),
    .B(_0008_),
    .Y(_0009_)
  );
  sky130_fd_sc_hd__a21oi_1 _0598_ (
    .A1(_0506_),
    .A2(_0007_),
    .B1(_0009_),
    .Y(_0010_)
  );
  sky130_fd_sc_hd__nor2_1 _0599_ (
    .A(\alu_inst.b_i [4]),
    .B(_0010_),
    .Y(_0011_)
  );
  sky130_fd_sc_hd__xor2_1 _0600_ (
    .A(\alu_inst.b_i [4]),
    .B(_0010_),
    .X(_0012_)
  );
  sky130_fd_sc_hd__xnor2_1 _0601_ (
    .A(_0318_),
    .B(_0511_),
    .Y(_0013_)
  );
  sky130_fd_sc_hd__xnor2_1 _0602_ (
    .A(_0520_),
    .B(_0013_),
    .Y(_0014_)
  );
  sky130_fd_sc_hd__mux2i_1 _0603_ (
    .A0(_0014_),
    .A1(_0511_),
    .S(_0007_),
    .Y(_0015_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0604_ (
    .A(\alu_inst.b_i [3]),
    .SLEEP(_0015_),
    .X(_0016_)
  );
  sky130_fd_sc_hd__nand2_1 _0605_ (
    .A(\alu_inst.b_i [3]),
    .B(_0015_),
    .Y(_0017_)
  );
  sky130_fd_sc_hd__xnor2_1 _0606_ (
    .A(_0517_),
    .B(_0519_),
    .Y(_0018_)
  );
  sky130_fd_sc_hd__mux2i_1 _0607_ (
    .A0(_0018_),
    .A1(_0515_),
    .S(_0007_),
    .Y(_0019_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0608_ (
    .A(\alu_inst.b_i [2]),
    .SLEEP(_0019_),
    .X(_0020_)
  );
  sky130_fd_sc_hd__xnor2_1 _0609_ (
    .A(\alu_inst.b_i [2]),
    .B(_0019_),
    .Y(_0021_)
  );
  sky130_fd_sc_hd__o211ai_1 _0610_ (
    .A1(_0000_),
    .A2(_0005_),
    .B1(_0006_),
    .C1(\alu_inst.b_i [0]),
    .Y(_0022_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _0611_ (
    .A1_N(_0517_),
    .A2_N(_0007_),
    .B1(_0022_),
    .B2(\alu_inst.a_i [3]),
    .Y(_0023_)
  );
  sky130_fd_sc_hd__nor2_1 _0612_ (
    .A(_0254_),
    .B(\alu_inst.a_i [2]),
    .Y(_0024_)
  );
  sky130_fd_sc_hd__xnor2_1 _0613_ (
    .A(\alu_inst.b_i [1]),
    .B(_0023_),
    .Y(_0025_)
  );
  sky130_fd_sc_hd__maj3_1 _0614_ (
    .A(\alu_inst.b_i [1]),
    .B(_0023_),
    .C(_0024_),
    .X(_0026_)
  );
  sky130_fd_sc_hd__o21a_1 _0615_ (
    .A1(_0021_),
    .A2(_0026_),
    .B1(_0020_),
    .X(_0027_)
  );
  sky130_fd_sc_hd__o211ai_1 _0616_ (
    .A1(_0021_),
    .A2(_0026_),
    .B1(_0016_),
    .C1(_0020_),
    .Y(_0028_)
  );
  sky130_fd_sc_hd__nand2_1 _0617_ (
    .A(_0017_),
    .B(_0028_),
    .Y(_0029_)
  );
  sky130_fd_sc_hd__a31oi_1 _0618_ (
    .A1(_0012_),
    .A2(_0017_),
    .A3(_0028_),
    .B1(_0011_),
    .Y(_0030_)
  );
  sky130_fd_sc_hd__a311oi_1 _0619_ (
    .A1(_0012_),
    .A2(_0017_),
    .A3(_0028_),
    .B1(_0011_),
    .C1(_0004_),
    .Y(_0031_)
  );
  sky130_fd_sc_hd__o21ai_0 _0620_ (
    .A1(_0500_),
    .A2(_0002_),
    .B1(\alu_inst.b_i [5]),
    .Y(_0032_)
  );
  sky130_fd_sc_hd__nand2_1 _0621_ (
    .A(_0329_),
    .B(_0032_),
    .Y(_0033_)
  );
  sky130_fd_sc_hd__nor2_1 _0622_ (
    .A(_0031_),
    .B(_0033_),
    .Y(_0034_)
  );
  sky130_fd_sc_hd__xor2_1 _0623_ (
    .A(_0012_),
    .B(_0029_),
    .X(_0035_)
  );
  sky130_fd_sc_hd__mux2_1 _0624_ (
    .A0(_0010_),
    .A1(_0035_),
    .S(_0034_),
    .X(_0036_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0625_ (
    .A(\alu_inst.b_i [5]),
    .SLEEP(_0036_),
    .X(_0037_)
  );
  sky130_fd_sc_hd__nand2_1 _0626_ (
    .A(\alu_inst.b_i [5]),
    .B(_0036_),
    .Y(_0038_)
  );
  sky130_fd_sc_hd__nand2_1 _0627_ (
    .A(_0037_),
    .B(_0038_),
    .Y(_0039_)
  );
  sky130_fd_sc_hd__nand2_1 _0628_ (
    .A(_0016_),
    .B(_0017_),
    .Y(_0040_)
  );
  sky130_fd_sc_hd__xnor2_1 _0629_ (
    .A(_0027_),
    .B(_0040_),
    .Y(_0041_)
  );
  sky130_fd_sc_hd__mux2_1 _0630_ (
    .A0(_0015_),
    .A1(_0041_),
    .S(_0034_),
    .X(_0042_)
  );
  sky130_fd_sc_hd__nor2_1 _0631_ (
    .A(\alu_inst.b_i [4]),
    .B(_0042_),
    .Y(_0043_)
  );
  sky130_fd_sc_hd__and2_0 _0632_ (
    .A(\alu_inst.b_i [4]),
    .B(_0042_),
    .X(_0044_)
  );
  sky130_fd_sc_hd__xnor2_1 _0633_ (
    .A(_0021_),
    .B(_0026_),
    .Y(_0045_)
  );
  sky130_fd_sc_hd__mux2_1 _0634_ (
    .A0(_0019_),
    .A1(_0045_),
    .S(_0034_),
    .X(_0046_)
  );
  sky130_fd_sc_hd__nor2_1 _0635_ (
    .A(\alu_inst.b_i [3]),
    .B(_0046_),
    .Y(_0047_)
  );
  sky130_fd_sc_hd__xor2_1 _0636_ (
    .A(\alu_inst.b_i [3]),
    .B(_0046_),
    .X(_0048_)
  );
  sky130_fd_sc_hd__xnor2_1 _0637_ (
    .A(_0024_),
    .B(_0025_),
    .Y(_0049_)
  );
  sky130_fd_sc_hd__mux2i_1 _0638_ (
    .A0(_0023_),
    .A1(_0049_),
    .S(_0034_),
    .Y(_0050_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0639_ (
    .A(_0318_),
    .SLEEP(_0050_),
    .X(_0051_)
  );
  sky130_fd_sc_hd__o31a_1 _0640_ (
    .A1(_0254_),
    .A2(_0031_),
    .A3(_0033_),
    .B1(\alu_inst.a_i [2]),
    .X(_0052_)
  );
  sky130_fd_sc_hd__nor4_1 _0641_ (
    .A(_0254_),
    .B(\alu_inst.a_i [2]),
    .C(_0031_),
    .D(_0033_),
    .Y(_0053_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0642_ (
    .A(_0052_),
    .SLEEP(_0053_),
    .X(_0054_)
  );
  sky130_fd_sc_hd__o21a_1 _0643_ (
    .A1(_0052_),
    .A2(_0053_),
    .B1(_0308_),
    .X(_0055_)
  );
  sky130_fd_sc_hd__nand2b_1 _0644_ (
    .A_N(\alu_inst.a_i [1]),
    .B(\alu_inst.b_i [0]),
    .Y(_0056_)
  );
  sky130_fd_sc_hd__or3_1 _0645_ (
    .A(_0308_),
    .B(_0052_),
    .C(_0053_),
    .X(_0057_)
  );
  sky130_fd_sc_hd__nor2b_1 _0646_ (
    .A(_0055_),
    .B_N(_0057_),
    .Y(_0058_)
  );
  sky130_fd_sc_hd__a21o_1 _0647_ (
    .A1(_0056_),
    .A2(_0057_),
    .B1(_0055_),
    .X(_0059_)
  );
  sky130_fd_sc_hd__a221o_1 _0648_ (
    .A1(_0318_),
    .A2(_0050_),
    .B1(_0056_),
    .B2(_0057_),
    .C1(_0055_),
    .X(_0060_)
  );
  sky130_fd_sc_hd__nand3_1 _0649_ (
    .A(_0048_),
    .B(_0051_),
    .C(_0060_),
    .Y(_0061_)
  );
  sky130_fd_sc_hd__o21ai_0 _0650_ (
    .A1(\alu_inst.b_i [3]),
    .A2(_0046_),
    .B1(_0061_),
    .Y(_0062_)
  );
  sky130_fd_sc_hd__a311oi_1 _0651_ (
    .A1(_0048_),
    .A2(_0051_),
    .A3(_0060_),
    .B1(_0047_),
    .C1(_0043_),
    .Y(_0063_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0652_ (
    .A(_0044_),
    .SLEEP(_0063_),
    .X(_0064_)
  );
  sky130_fd_sc_hd__o31ai_1 _0653_ (
    .A1(_0039_),
    .A2(_0044_),
    .A3(_0063_),
    .B1(_0037_),
    .Y(_0065_)
  );
  sky130_fd_sc_hd__nand2_1 _0654_ (
    .A(\alu_inst.b_i [5]),
    .B(_0329_),
    .Y(_0066_)
  );
  sky130_fd_sc_hd__mux2_1 _0655_ (
    .A0(_0066_),
    .A1(_0340_),
    .S(_0030_),
    .X(_0067_)
  );
  sky130_fd_sc_hd__nand2_1 _0656_ (
    .A(_0003_),
    .B(_0067_),
    .Y(_0068_)
  );
  sky130_fd_sc_hd__nor2_1 _0657_ (
    .A(\alu_inst.b_i [6]),
    .B(_0068_),
    .Y(_0069_)
  );
  sky130_fd_sc_hd__a21oi_1 _0658_ (
    .A1(\alu_inst.b_i [6]),
    .A2(_0068_),
    .B1(\alu_inst.b_i [7]),
    .Y(_0070_)
  );
  sky130_fd_sc_hd__o21ai_0 _0659_ (
    .A1(_0065_),
    .A2(_0069_),
    .B1(_0070_),
    .Y(_0071_)
  );
  sky130_fd_sc_hd__a21oi_1 _0660_ (
    .A1(_0051_),
    .A2(_0060_),
    .B1(_0048_),
    .Y(_0072_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0661_ (
    .A(_0061_),
    .SLEEP(_0072_),
    .X(_0073_)
  );
  sky130_fd_sc_hd__nand2_1 _0662_ (
    .A(_0046_),
    .B(_0071_),
    .Y(_0074_)
  );
  sky130_fd_sc_hd__o21ai_0 _0663_ (
    .A1(_0071_),
    .A2(_0073_),
    .B1(_0074_),
    .Y(_0075_)
  );
  sky130_fd_sc_hd__nand2_1 _0664_ (
    .A(\alu_inst.b_i [4]),
    .B(_0075_),
    .Y(_0076_)
  );
  sky130_fd_sc_hd__xnor2_1 _0665_ (
    .A(\alu_inst.b_i [2]),
    .B(_0050_),
    .Y(_0077_)
  );
  sky130_fd_sc_hd__xor2_1 _0666_ (
    .A(_0059_),
    .B(_0077_),
    .X(_0078_)
  );
  sky130_fd_sc_hd__mux2i_1 _0667_ (
    .A0(_0078_),
    .A1(_0050_),
    .S(_0071_),
    .Y(_0079_)
  );
  sky130_fd_sc_hd__nor2_1 _0668_ (
    .A(_0254_),
    .B(\alu_inst.a_i [0]),
    .Y(_0080_)
  );
  sky130_fd_sc_hd__nand2_1 _0669_ (
    .A(\alu_inst.b_i [1]),
    .B(_0080_),
    .Y(_0081_)
  );
  sky130_fd_sc_hd__o211ai_1 _0670_ (
    .A1(_0065_),
    .A2(_0069_),
    .B1(_0070_),
    .C1(\alu_inst.b_i [0]),
    .Y(_0082_)
  );
  sky130_fd_sc_hd__xnor2_1 _0671_ (
    .A(\alu_inst.a_i [1]),
    .B(_0082_),
    .Y(_0083_)
  );
  sky130_fd_sc_hd__xor2_1 _0672_ (
    .A(_0056_),
    .B(_0058_),
    .X(_0084_)
  );
  sky130_fd_sc_hd__mux2_1 _0673_ (
    .A0(_0084_),
    .A1(_0054_),
    .S(_0071_),
    .X(_0085_)
  );
  sky130_fd_sc_hd__nor2_1 _0674_ (
    .A(\alu_inst.b_i [1]),
    .B(_0080_),
    .Y(_0086_)
  );
  sky130_fd_sc_hd__a221oi_1 _0675_ (
    .A1(_0081_),
    .A2(_0083_),
    .B1(_0085_),
    .B2(_0318_),
    .C1(_0086_),
    .Y(_0087_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _0676_ (
    .A1_N(\alu_inst.b_i [3]),
    .A2_N(_0079_),
    .B1(_0085_),
    .B2(_0318_),
    .Y(_0088_)
  );
  sky130_fd_sc_hd__o22ai_1 _0677_ (
    .A1(\alu_inst.b_i [3]),
    .A2(_0079_),
    .B1(_0087_),
    .B2(_0088_),
    .Y(_0089_)
  );
  sky130_fd_sc_hd__nor2_1 _0678_ (
    .A(_0043_),
    .B(_0044_),
    .Y(_0090_)
  );
  sky130_fd_sc_hd__xnor2_1 _0679_ (
    .A(_0062_),
    .B(_0090_),
    .Y(_0091_)
  );
  sky130_fd_sc_hd__mux2_1 _0680_ (
    .A0(_0091_),
    .A1(_0042_),
    .S(_0071_),
    .X(_0092_)
  );
  sky130_fd_sc_hd__o22ai_1 _0681_ (
    .A1(\alu_inst.b_i [4]),
    .A2(_0075_),
    .B1(_0092_),
    .B2(\alu_inst.b_i [5]),
    .Y(_0093_)
  );
  sky130_fd_sc_hd__a21o_1 _0682_ (
    .A1(_0076_),
    .A2(_0089_),
    .B1(_0093_),
    .X(_0094_)
  );
  sky130_fd_sc_hd__xnor2_1 _0683_ (
    .A(_0039_),
    .B(_0064_),
    .Y(_0095_)
  );
  sky130_fd_sc_hd__mux2_1 _0684_ (
    .A0(_0095_),
    .A1(_0036_),
    .S(_0071_),
    .X(_0096_)
  );
  sky130_fd_sc_hd__a22oi_1 _0685_ (
    .A1(\alu_inst.b_i [5]),
    .A2(_0092_),
    .B1(_0096_),
    .B2(\alu_inst.b_i [6]),
    .Y(_0097_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0686_ (
    .A(\alu_inst.b_i [6]),
    .SLEEP(\alu_inst.b_i [7]),
    .X(_0098_)
  );
  sky130_fd_sc_hd__mux2_1 _0687_ (
    .A0(_0329_),
    .A1(_0098_),
    .S(_0065_),
    .X(_0099_)
  );
  sky130_fd_sc_hd__a21oi_1 _0688_ (
    .A1(_0065_),
    .A2(_0098_),
    .B1(_0068_),
    .Y(_0100_)
  );
  sky130_fd_sc_hd__o32ai_1 _0689_ (
    .A1(\alu_inst.b_i [7]),
    .A2(_0068_),
    .A3(_0099_),
    .B1(_0096_),
    .B2(\alu_inst.b_i [6]),
    .Y(_0101_)
  );
  sky130_fd_sc_hd__a21oi_1 _0690_ (
    .A1(_0094_),
    .A2(_0097_),
    .B1(_0101_),
    .Y(_0102_)
  );
  sky130_fd_sc_hd__nand2_1 _0691_ (
    .A(\alu_inst.op_i [1]),
    .B(\alu_inst.op_i [0]),
    .Y(_0103_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0692_ (
    .A(\alu_inst.b_i [7]),
    .SLEEP(\alu_inst.a_i [7]),
    .X(_0104_)
  );
  sky130_fd_sc_hd__nand2_1 _0693_ (
    .A(\alu_inst.b_i [0]),
    .B(\alu_inst.a_i [0]),
    .Y(_0105_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0694_ (
    .A(\alu_inst.op_i [1]),
    .SLEEP(\alu_inst.op_i [0]),
    .X(_0106_)
  );
  sky130_fd_sc_hd__nand2b_1 _0695_ (
    .A_N(\alu_inst.op_i [0]),
    .B(\alu_inst.op_i [1]),
    .Y(_0107_)
  );
  sky130_fd_sc_hd__xnor2_1 _0696_ (
    .A(\alu_inst.b_i [0]),
    .B(\alu_inst.a_i [0]),
    .Y(_0108_)
  );
  sky130_fd_sc_hd__o22a_1 _0697_ (
    .A1(_0105_),
    .A2(_0107_),
    .B1(_0108_),
    .B2(\alu_inst.op_i [1]),
    .X(_0109_)
  );
  sky130_fd_sc_hd__o31ai_1 _0698_ (
    .A1(_0102_),
    .A2(_0103_),
    .A3(_0104_),
    .B1(_0109_),
    .Y(\alu_inst.r_o [0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0699_ (
    .A(\alu_inst.a_i [1]),
    .SLEEP(\alu_inst.b_i [1]),
    .X(_0110_)
  );
  sky130_fd_sc_hd__xor2_1 _0700_ (
    .A(\alu_inst.b_i [1]),
    .B(\alu_inst.a_i [1]),
    .X(_0111_)
  );
  sky130_fd_sc_hd__nor2_1 _0701_ (
    .A(_0080_),
    .B(_0111_),
    .Y(_0112_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0702_ (
    .A(\alu_inst.op_i [0]),
    .SLEEP(\alu_inst.op_i [1]),
    .X(_0113_)
  );
  sky130_fd_sc_hd__xor2_1 _0703_ (
    .A(_0080_),
    .B(_0111_),
    .X(_0114_)
  );
  sky130_fd_sc_hd__a21oi_1 _0704_ (
    .A1(\alu_inst.b_i [0]),
    .A2(\alu_inst.a_i [0]),
    .B1(_0111_),
    .Y(_0115_)
  );
  sky130_fd_sc_hd__nand3_1 _0705_ (
    .A(\alu_inst.b_i [0]),
    .B(\alu_inst.a_i [0]),
    .C(_0111_),
    .Y(_0116_)
  );
  sky130_fd_sc_hd__nor2_1 _0706_ (
    .A(\alu_inst.op_i [1]),
    .B(\alu_inst.op_i [0]),
    .Y(_0117_)
  );
  sky130_fd_sc_hd__nand2_1 _0707_ (
    .A(_0116_),
    .B(_0117_),
    .Y(_0118_)
  );
  sky130_fd_sc_hd__nand2_1 _0708_ (
    .A(\alu_inst.b_i [1]),
    .B(\alu_inst.a_i [1]),
    .Y(_0119_)
  );
  sky130_fd_sc_hd__nor2_1 _0709_ (
    .A(_0105_),
    .B(_0119_),
    .Y(_0120_)
  );
  sky130_fd_sc_hd__a22oi_1 _0710_ (
    .A1(\alu_inst.a_i [0]),
    .A2(\alu_inst.b_i [1]),
    .B1(\alu_inst.a_i [1]),
    .B2(\alu_inst.b_i [0]),
    .Y(_0121_)
  );
  sky130_fd_sc_hd__o32ai_1 _0711_ (
    .A1(_0107_),
    .A2(_0120_),
    .A3(_0121_),
    .B1(_0115_),
    .B2(_0118_),
    .Y(_0122_)
  );
  sky130_fd_sc_hd__a21oi_1 _0712_ (
    .A1(_0113_),
    .A2(_0114_),
    .B1(_0122_),
    .Y(_0123_)
  );
  sky130_fd_sc_hd__o21ai_0 _0713_ (
    .A1(_0071_),
    .A2(_0103_),
    .B1(_0123_),
    .Y(\alu_inst.r_o [1])
  );
  sky130_fd_sc_hd__nand3_1 _0714_ (
    .A(\alu_inst.op_i [1]),
    .B(\alu_inst.op_i [0]),
    .C(_0034_),
    .Y(_0124_)
  );
  sky130_fd_sc_hd__nand2_1 _0715_ (
    .A(\alu_inst.a_i [0]),
    .B(\alu_inst.b_i [2]),
    .Y(_0125_)
  );
  sky130_fd_sc_hd__nand2_1 _0716_ (
    .A(\alu_inst.b_i [0]),
    .B(\alu_inst.a_i [2]),
    .Y(_0126_)
  );
  sky130_fd_sc_hd__nand2_1 _0717_ (
    .A(\alu_inst.a_i [2]),
    .B(\alu_inst.b_i [1]),
    .Y(_0127_)
  );
  sky130_fd_sc_hd__xnor2_1 _0718_ (
    .A(_0119_),
    .B(_0126_),
    .Y(_0128_)
  );
  sky130_fd_sc_hd__xnor2_1 _0719_ (
    .A(_0125_),
    .B(_0128_),
    .Y(_0129_)
  );
  sky130_fd_sc_hd__o21ai_0 _0720_ (
    .A1(_0105_),
    .A2(_0119_),
    .B1(_0129_),
    .Y(_0130_)
  );
  sky130_fd_sc_hd__or3_1 _0721_ (
    .A(_0105_),
    .B(_0119_),
    .C(_0129_),
    .X(_0131_)
  );
  sky130_fd_sc_hd__nand3_1 _0722_ (
    .A(_0106_),
    .B(_0130_),
    .C(_0131_),
    .Y(_0132_)
  );
  sky130_fd_sc_hd__xnor2_1 _0723_ (
    .A(\alu_inst.a_i [2]),
    .B(\alu_inst.b_i [2]),
    .Y(_0133_)
  );
  sky130_fd_sc_hd__a21o_1 _0724_ (
    .A1(_0116_),
    .A2(_0119_),
    .B1(_0133_),
    .X(_0134_)
  );
  sky130_fd_sc_hd__nand2_1 _0725_ (
    .A(_0117_),
    .B(_0134_),
    .Y(_0135_)
  );
  sky130_fd_sc_hd__a31oi_1 _0726_ (
    .A1(_0116_),
    .A2(_0119_),
    .A3(_0133_),
    .B1(_0135_),
    .Y(_0136_)
  );
  sky130_fd_sc_hd__or3_1 _0727_ (
    .A(_0110_),
    .B(_0112_),
    .C(_0133_),
    .X(_0137_)
  );
  sky130_fd_sc_hd__o21ai_0 _0728_ (
    .A1(_0110_),
    .A2(_0112_),
    .B1(_0133_),
    .Y(_0138_)
  );
  sky130_fd_sc_hd__a31oi_1 _0729_ (
    .A1(_0113_),
    .A2(_0137_),
    .A3(_0138_),
    .B1(_0136_),
    .Y(_0139_)
  );
  sky130_fd_sc_hd__nand3_1 _0730_ (
    .A(_0124_),
    .B(_0132_),
    .C(_0139_),
    .Y(\alu_inst.r_o [2])
  );
  sky130_fd_sc_hd__nand2_1 _0731_ (
    .A(\alu_inst.a_i [0]),
    .B(\alu_inst.b_i [3]),
    .Y(_0140_)
  );
  sky130_fd_sc_hd__maj3_1 _0732_ (
    .A(_0119_),
    .B(_0125_),
    .C(_0126_),
    .X(_0141_)
  );
  sky130_fd_sc_hd__nand2_1 _0733_ (
    .A(\alu_inst.b_i [2]),
    .B(\alu_inst.a_i [1]),
    .Y(_0142_)
  );
  sky130_fd_sc_hd__nand2_1 _0734_ (
    .A(\alu_inst.b_i [0]),
    .B(\alu_inst.a_i [3]),
    .Y(_0143_)
  );
  sky130_fd_sc_hd__xnor2_1 _0735_ (
    .A(_0127_),
    .B(_0143_),
    .Y(_0144_)
  );
  sky130_fd_sc_hd__xnor2_1 _0736_ (
    .A(_0142_),
    .B(_0144_),
    .Y(_0145_)
  );
  sky130_fd_sc_hd__xnor2_1 _0737_ (
    .A(_0141_),
    .B(_0145_),
    .Y(_0146_)
  );
  sky130_fd_sc_hd__xnor2_1 _0738_ (
    .A(_0140_),
    .B(_0146_),
    .Y(_0147_)
  );
  sky130_fd_sc_hd__nor2_1 _0739_ (
    .A(_0131_),
    .B(_0147_),
    .Y(_0148_)
  );
  sky130_fd_sc_hd__xnor2_1 _0740_ (
    .A(_0131_),
    .B(_0147_),
    .Y(_0149_)
  );
  sky130_fd_sc_hd__nor2_1 _0741_ (
    .A(_0286_),
    .B(\alu_inst.b_i [3]),
    .Y(_0150_)
  );
  sky130_fd_sc_hd__nand2_1 _0742_ (
    .A(_0286_),
    .B(\alu_inst.b_i [3]),
    .Y(_0151_)
  );
  sky130_fd_sc_hd__nor2b_1 _0743_ (
    .A(_0150_),
    .B_N(_0151_),
    .Y(_0152_)
  );
  sky130_fd_sc_hd__o21ai_0 _0744_ (
    .A1(_0297_),
    .A2(\alu_inst.b_i [2]),
    .B1(_0138_),
    .Y(_0153_)
  );
  sky130_fd_sc_hd__xor2_1 _0745_ (
    .A(_0152_),
    .B(_0153_),
    .X(_0154_)
  );
  sky130_fd_sc_hd__nand2_1 _0746_ (
    .A(\alu_inst.a_i [2]),
    .B(\alu_inst.b_i [2]),
    .Y(_0155_)
  );
  sky130_fd_sc_hd__a21o_1 _0747_ (
    .A1(_0134_),
    .A2(_0155_),
    .B1(_0152_),
    .X(_0156_)
  );
  sky130_fd_sc_hd__nand3_1 _0748_ (
    .A(_0134_),
    .B(_0152_),
    .C(_0155_),
    .Y(_0157_)
  );
  sky130_fd_sc_hd__a32oi_1 _0749_ (
    .A1(_0117_),
    .A2(_0156_),
    .A3(_0157_),
    .B1(_0154_),
    .B2(_0113_),
    .Y(_0158_)
  );
  sky130_fd_sc_hd__o221ai_1 _0750_ (
    .A1(_0007_),
    .A2(_0103_),
    .B1(_0107_),
    .B2(_0149_),
    .C1(_0158_),
    .Y(\alu_inst.r_o [3])
  );
  sky130_fd_sc_hd__maj3_1 _0751_ (
    .A(_0140_),
    .B(_0141_),
    .C(_0145_),
    .X(_0159_)
  );
  sky130_fd_sc_hd__a22o_1 _0752_ (
    .A1(\alu_inst.a_i [0]),
    .A2(\alu_inst.b_i [4]),
    .B1(\alu_inst.b_i [3]),
    .B2(\alu_inst.a_i [1]),
    .X(_0160_)
  );
  sky130_fd_sc_hd__nand2_1 _0753_ (
    .A(\alu_inst.b_i [4]),
    .B(\alu_inst.a_i [1]),
    .Y(_0161_)
  );
  sky130_fd_sc_hd__nand4_1 _0754_ (
    .A(\alu_inst.a_i [0]),
    .B(\alu_inst.b_i [4]),
    .C(\alu_inst.b_i [3]),
    .D(\alu_inst.a_i [1]),
    .Y(_0162_)
  );
  sky130_fd_sc_hd__nand2_1 _0755_ (
    .A(_0160_),
    .B(_0162_),
    .Y(_0163_)
  );
  sky130_fd_sc_hd__maj3_1 _0756_ (
    .A(_0127_),
    .B(_0142_),
    .C(_0143_),
    .X(_0164_)
  );
  sky130_fd_sc_hd__a22oi_1 _0757_ (
    .A1(\alu_inst.b_i [0]),
    .A2(\alu_inst.a_i [4]),
    .B1(\alu_inst.a_i [3]),
    .B2(\alu_inst.b_i [1]),
    .Y(_0165_)
  );
  sky130_fd_sc_hd__nand2_1 _0758_ (
    .A(\alu_inst.a_i [4]),
    .B(\alu_inst.b_i [1]),
    .Y(_0166_)
  );
  sky130_fd_sc_hd__o21bai_1 _0759_ (
    .A1(_0143_),
    .A2(_0166_),
    .B1_N(_0165_),
    .Y(_0167_)
  );
  sky130_fd_sc_hd__xnor2_1 _0760_ (
    .A(_0155_),
    .B(_0167_),
    .Y(_0168_)
  );
  sky130_fd_sc_hd__xnor2_1 _0761_ (
    .A(_0164_),
    .B(_0168_),
    .Y(_0169_)
  );
  sky130_fd_sc_hd__xor2_1 _0762_ (
    .A(_0163_),
    .B(_0169_),
    .X(_0170_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0763_ (
    .A(_0170_),
    .SLEEP(_0159_),
    .X(_0171_)
  );
  sky130_fd_sc_hd__xnor2_1 _0764_ (
    .A(_0159_),
    .B(_0170_),
    .Y(_0172_)
  );
  sky130_fd_sc_hd__nand2_1 _0765_ (
    .A(_0148_),
    .B(_0172_),
    .Y(_0173_)
  );
  sky130_fd_sc_hd__a21oi_1 _0766_ (
    .A1(_0148_),
    .A2(_0172_),
    .B1(_0107_),
    .Y(_0174_)
  );
  sky130_fd_sc_hd__o21ai_0 _0767_ (
    .A1(_0148_),
    .A2(_0172_),
    .B1(_0174_),
    .Y(_0175_)
  );
  sky130_fd_sc_hd__xnor2_1 _0768_ (
    .A(\alu_inst.a_i [4]),
    .B(\alu_inst.b_i [4]),
    .Y(_0176_)
  );
  sky130_fd_sc_hd__nand2_1 _0769_ (
    .A(\alu_inst.a_i [3]),
    .B(\alu_inst.b_i [3]),
    .Y(_0177_)
  );
  sky130_fd_sc_hd__nand3_1 _0770_ (
    .A(_0156_),
    .B(_0176_),
    .C(_0177_),
    .Y(_0178_)
  );
  sky130_fd_sc_hd__a21o_1 _0771_ (
    .A1(_0156_),
    .A2(_0177_),
    .B1(_0176_),
    .X(_0179_)
  );
  sky130_fd_sc_hd__o21ai_0 _0772_ (
    .A1(_0150_),
    .A2(_0153_),
    .B1(_0151_),
    .Y(_0180_)
  );
  sky130_fd_sc_hd__nand2b_1 _0773_ (
    .A_N(_0180_),
    .B(_0176_),
    .Y(_0181_)
  );
  sky130_fd_sc_hd__xnor2_1 _0774_ (
    .A(_0176_),
    .B(_0180_),
    .Y(_0182_)
  );
  sky130_fd_sc_hd__a32oi_1 _0775_ (
    .A1(_0117_),
    .A2(_0178_),
    .A3(_0179_),
    .B1(_0182_),
    .B2(_0113_),
    .Y(_0183_)
  );
  sky130_fd_sc_hd__o211ai_1 _0776_ (
    .A1(_0503_),
    .A2(_0103_),
    .B1(_0175_),
    .C1(_0183_),
    .Y(\alu_inst.r_o [4])
  );
  sky130_fd_sc_hd__maj3_1 _0777_ (
    .A(_0163_),
    .B(_0164_),
    .C(_0168_),
    .X(_0184_)
  );
  sky130_fd_sc_hd__nand2_1 _0778_ (
    .A(\alu_inst.a_i [0]),
    .B(\alu_inst.b_i [5]),
    .Y(_0185_)
  );
  sky130_fd_sc_hd__nand2_1 _0779_ (
    .A(\alu_inst.a_i [2]),
    .B(\alu_inst.b_i [3]),
    .Y(_0186_)
  );
  sky130_fd_sc_hd__nand2_1 _0780_ (
    .A(\alu_inst.a_i [2]),
    .B(\alu_inst.b_i [4]),
    .Y(_0187_)
  );
  sky130_fd_sc_hd__xnor2_1 _0781_ (
    .A(_0161_),
    .B(_0186_),
    .Y(_0188_)
  );
  sky130_fd_sc_hd__xnor2_1 _0782_ (
    .A(_0185_),
    .B(_0188_),
    .Y(_0189_)
  );
  sky130_fd_sc_hd__o22a_1 _0783_ (
    .A1(_0143_),
    .A2(_0166_),
    .B1(_0167_),
    .B2(_0155_),
    .X(_0190_)
  );
  sky130_fd_sc_hd__nand2_1 _0784_ (
    .A(\alu_inst.a_i [3]),
    .B(\alu_inst.b_i [2]),
    .Y(_0191_)
  );
  sky130_fd_sc_hd__xor2_1 _0785_ (
    .A(_0467_),
    .B(_0166_),
    .X(_0192_)
  );
  sky130_fd_sc_hd__xnor2_1 _0786_ (
    .A(_0191_),
    .B(_0192_),
    .Y(_0193_)
  );
  sky130_fd_sc_hd__clkinv_1 _0787_ (
    .A(_0193_),
    .Y(_0194_)
  );
  sky130_fd_sc_hd__xnor2_1 _0788_ (
    .A(_0190_),
    .B(_0193_),
    .Y(_0195_)
  );
  sky130_fd_sc_hd__xnor2_1 _0789_ (
    .A(_0189_),
    .B(_0195_),
    .Y(_0196_)
  );
  sky130_fd_sc_hd__clkinv_1 _0790_ (
    .A(_0196_),
    .Y(_0197_)
  );
  sky130_fd_sc_hd__xnor2_1 _0791_ (
    .A(_0184_),
    .B(_0196_),
    .Y(_0198_)
  );
  sky130_fd_sc_hd__xnor2_1 _0792_ (
    .A(_0162_),
    .B(_0198_),
    .Y(_0199_)
  );
  sky130_fd_sc_hd__nand2_1 _0793_ (
    .A(_0171_),
    .B(_0199_),
    .Y(_0200_)
  );
  sky130_fd_sc_hd__xnor2_1 _0794_ (
    .A(_0171_),
    .B(_0199_),
    .Y(_0201_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0795_ (
    .A(_0173_),
    .SLEEP(_0201_),
    .X(_0202_)
  );
  sky130_fd_sc_hd__a21oi_1 _0796_ (
    .A1(_0173_),
    .A2(_0201_),
    .B1(_0107_),
    .Y(_0203_)
  );
  sky130_fd_sc_hd__xnor2_1 _0797_ (
    .A(\alu_inst.a_i [5]),
    .B(\alu_inst.b_i [5]),
    .Y(_0204_)
  );
  sky130_fd_sc_hd__nand2_1 _0798_ (
    .A(\alu_inst.a_i [4]),
    .B(\alu_inst.b_i [4]),
    .Y(_0205_)
  );
  sky130_fd_sc_hd__a21o_1 _0799_ (
    .A1(_0179_),
    .A2(_0205_),
    .B1(_0204_),
    .X(_0206_)
  );
  sky130_fd_sc_hd__nand3_1 _0800_ (
    .A(_0179_),
    .B(_0204_),
    .C(_0205_),
    .Y(_0207_)
  );
  sky130_fd_sc_hd__nand3_1 _0801_ (
    .A(_0117_),
    .B(_0206_),
    .C(_0207_),
    .Y(_0208_)
  );
  sky130_fd_sc_hd__o21ai_0 _0802_ (
    .A1(_0275_),
    .A2(\alu_inst.b_i [4]),
    .B1(_0181_),
    .Y(_0209_)
  );
  sky130_fd_sc_hd__nor2_1 _0803_ (
    .A(_0204_),
    .B(_0209_),
    .Y(_0210_)
  );
  sky130_fd_sc_hd__nand2_1 _0804_ (
    .A(_0204_),
    .B(_0209_),
    .Y(_0211_)
  );
  sky130_fd_sc_hd__nand2_1 _0805_ (
    .A(_0113_),
    .B(_0211_),
    .Y(_0212_)
  );
  sky130_fd_sc_hd__o21ai_0 _0806_ (
    .A1(_0210_),
    .A2(_0212_),
    .B1(_0208_),
    .Y(_0213_)
  );
  sky130_fd_sc_hd__a21oi_1 _0807_ (
    .A1(_0202_),
    .A2(_0203_),
    .B1(_0213_),
    .Y(_0214_)
  );
  sky130_fd_sc_hd__o21ai_0 _0808_ (
    .A1(_0488_),
    .A2(_0103_),
    .B1(_0214_),
    .Y(\alu_inst.r_o [5])
  );
  sky130_fd_sc_hd__maj3_1 _0809_ (
    .A(_0162_),
    .B(_0184_),
    .C(_0197_),
    .X(_0215_)
  );
  sky130_fd_sc_hd__nand2_1 _0810_ (
    .A(\alu_inst.a_i [0]),
    .B(\alu_inst.b_i [6]),
    .Y(_0216_)
  );
  sky130_fd_sc_hd__maj3_1 _0811_ (
    .A(_0161_),
    .B(_0185_),
    .C(_0186_),
    .X(_0217_)
  );
  sky130_fd_sc_hd__nor2_1 _0812_ (
    .A(_0216_),
    .B(_0217_),
    .Y(_0218_)
  );
  sky130_fd_sc_hd__xnor2_1 _0813_ (
    .A(_0216_),
    .B(_0217_),
    .Y(_0219_)
  );
  sky130_fd_sc_hd__maj3_1 _0814_ (
    .A(_0189_),
    .B(_0190_),
    .C(_0194_),
    .X(_0220_)
  );
  sky130_fd_sc_hd__xor2_1 _0815_ (
    .A(_0177_),
    .B(_0187_),
    .X(_0221_)
  );
  sky130_fd_sc_hd__a21o_1 _0816_ (
    .A1(\alu_inst.b_i [5]),
    .A2(\alu_inst.a_i [1]),
    .B1(_0221_),
    .X(_0222_)
  );
  sky130_fd_sc_hd__nand3_1 _0817_ (
    .A(\alu_inst.b_i [5]),
    .B(\alu_inst.a_i [1]),
    .C(_0221_),
    .Y(_0223_)
  );
  sky130_fd_sc_hd__nand2_1 _0818_ (
    .A(_0222_),
    .B(_0223_),
    .Y(_0224_)
  );
  sky130_fd_sc_hd__maj3_1 _0819_ (
    .A(_0467_),
    .B(_0166_),
    .C(_0191_),
    .X(_0225_)
  );
  sky130_fd_sc_hd__nand2_1 _0820_ (
    .A(\alu_inst.a_i [4]),
    .B(\alu_inst.b_i [2]),
    .Y(_0226_)
  );
  sky130_fd_sc_hd__a22oi_1 _0821_ (
    .A1(\alu_inst.b_i [0]),
    .A2(\alu_inst.a_i [6]),
    .B1(\alu_inst.a_i [5]),
    .B2(\alu_inst.b_i [1]),
    .Y(_0227_)
  );
  sky130_fd_sc_hd__nand2_1 _0822_ (
    .A(\alu_inst.a_i [6]),
    .B(\alu_inst.b_i [1]),
    .Y(_0228_)
  );
  sky130_fd_sc_hd__nor2_1 _0823_ (
    .A(_0467_),
    .B(_0228_),
    .Y(_0229_)
  );
  sky130_fd_sc_hd__nor2_1 _0824_ (
    .A(_0227_),
    .B(_0229_),
    .Y(_0230_)
  );
  sky130_fd_sc_hd__nor3_1 _0825_ (
    .A(_0226_),
    .B(_0227_),
    .C(_0229_),
    .Y(_0231_)
  );
  sky130_fd_sc_hd__xor2_1 _0826_ (
    .A(_0226_),
    .B(_0230_),
    .X(_0232_)
  );
  sky130_fd_sc_hd__xnor2_1 _0827_ (
    .A(_0225_),
    .B(_0232_),
    .Y(_0233_)
  );
  sky130_fd_sc_hd__xor2_1 _0828_ (
    .A(_0224_),
    .B(_0233_),
    .X(_0234_)
  );
  sky130_fd_sc_hd__clkinv_1 _0829_ (
    .A(_0234_),
    .Y(_0235_)
  );
  sky130_fd_sc_hd__xor2_1 _0830_ (
    .A(_0220_),
    .B(_0234_),
    .X(_0236_)
  );
  sky130_fd_sc_hd__xnor2_1 _0831_ (
    .A(_0219_),
    .B(_0236_),
    .Y(_0237_)
  );
  sky130_fd_sc_hd__nor2_1 _0832_ (
    .A(_0215_),
    .B(_0237_),
    .Y(_0238_)
  );
  sky130_fd_sc_hd__xor2_1 _0833_ (
    .A(_0215_),
    .B(_0237_),
    .X(_0239_)
  );
  sky130_fd_sc_hd__nand3_1 _0834_ (
    .A(_0171_),
    .B(_0199_),
    .C(_0239_),
    .Y(_0240_)
  );
  sky130_fd_sc_hd__xor2_1 _0835_ (
    .A(_0200_),
    .B(_0239_),
    .X(_0241_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0836_ (
    .A(_0202_),
    .SLEEP(_0241_),
    .X(_0242_)
  );
  sky130_fd_sc_hd__a21oi_1 _0837_ (
    .A1(_0202_),
    .A2(_0241_),
    .B1(_0107_),
    .Y(_0243_)
  );
  sky130_fd_sc_hd__nand2_1 _0838_ (
    .A(_0242_),
    .B(_0243_),
    .Y(_0244_)
  );
  sky130_fd_sc_hd__nand2b_1 _0839_ (
    .A_N(\alu_inst.b_i [6]),
    .B(\alu_inst.a_i [6]),
    .Y(_0245_)
  );
  sky130_fd_sc_hd__xnor2_1 _0840_ (
    .A(\alu_inst.a_i [6]),
    .B(\alu_inst.b_i [6]),
    .Y(_0246_)
  );
  sky130_fd_sc_hd__nand2_1 _0841_ (
    .A(\alu_inst.a_i [5]),
    .B(\alu_inst.b_i [5]),
    .Y(_0247_)
  );
  sky130_fd_sc_hd__nand2_1 _0842_ (
    .A(_0206_),
    .B(_0247_),
    .Y(_0248_)
  );
  sky130_fd_sc_hd__xnor2_1 _0843_ (
    .A(_0246_),
    .B(_0248_),
    .Y(_0249_)
  );
  sky130_fd_sc_hd__o21ai_0 _0844_ (
    .A1(_0264_),
    .A2(\alu_inst.b_i [5]),
    .B1(_0211_),
    .Y(_0250_)
  );
  sky130_fd_sc_hd__nand2_1 _0845_ (
    .A(_0246_),
    .B(_0250_),
    .Y(_0251_)
  );
  sky130_fd_sc_hd__o21a_1 _0846_ (
    .A1(_0246_),
    .A2(_0250_),
    .B1(_0113_),
    .X(_0252_)
  );
  sky130_fd_sc_hd__a22oi_1 _0847_ (
    .A1(_0117_),
    .A2(_0249_),
    .B1(_0251_),
    .B2(_0252_),
    .Y(_0253_)
  );
  sky130_fd_sc_hd__o211ai_1 _0848_ (
    .A1(_0404_),
    .A2(_0103_),
    .B1(_0244_),
    .C1(_0253_),
    .Y(\alu_inst.r_o [6])
  );
  sky130_fd_sc_hd__maj3_1 _0849_ (
    .A(_0219_),
    .B(_0220_),
    .C(_0235_),
    .X(_0255_)
  );
  sky130_fd_sc_hd__nand2_1 _0850_ (
    .A(\alu_inst.a_i [0]),
    .B(\alu_inst.b_i [7]),
    .Y(_0256_)
  );
  sky130_fd_sc_hd__nand2_1 _0851_ (
    .A(\alu_inst.b_i [6]),
    .B(\alu_inst.a_i [1]),
    .Y(_0257_)
  );
  sky130_fd_sc_hd__o21ai_0 _0852_ (
    .A1(_0177_),
    .A2(_0187_),
    .B1(_0223_),
    .Y(_0258_)
  );
  sky130_fd_sc_hd__xor2_1 _0853_ (
    .A(_0257_),
    .B(_0258_),
    .X(_0259_)
  );
  sky130_fd_sc_hd__nor2_1 _0854_ (
    .A(_0256_),
    .B(_0259_),
    .Y(_0260_)
  );
  sky130_fd_sc_hd__xor2_1 _0855_ (
    .A(_0256_),
    .B(_0259_),
    .X(_0261_)
  );
  sky130_fd_sc_hd__maj3_1 _0856_ (
    .A(_0224_),
    .B(_0225_),
    .C(_0232_),
    .X(_0262_)
  );
  sky130_fd_sc_hd__a22oi_1 _0857_ (
    .A1(\alu_inst.a_i [3]),
    .A2(\alu_inst.b_i [4]),
    .B1(\alu_inst.b_i [3]),
    .B2(\alu_inst.a_i [4]),
    .Y(_0263_)
  );
  sky130_fd_sc_hd__nor2_1 _0858_ (
    .A(_0177_),
    .B(_0205_),
    .Y(_0265_)
  );
  sky130_fd_sc_hd__nor2_1 _0859_ (
    .A(_0263_),
    .B(_0265_),
    .Y(_0266_)
  );
  sky130_fd_sc_hd__a21oi_1 _0860_ (
    .A1(\alu_inst.a_i [2]),
    .A2(\alu_inst.b_i [5]),
    .B1(_0266_),
    .Y(_0267_)
  );
  sky130_fd_sc_hd__nand3_1 _0861_ (
    .A(\alu_inst.a_i [2]),
    .B(\alu_inst.b_i [5]),
    .C(_0266_),
    .Y(_0268_)
  );
  sky130_fd_sc_hd__nor2b_1 _0862_ (
    .A(_0267_),
    .B_N(_0268_),
    .Y(_0269_)
  );
  sky130_fd_sc_hd__nand2_1 _0863_ (
    .A(\alu_inst.a_i [5]),
    .B(\alu_inst.b_i [2]),
    .Y(_0270_)
  );
  sky130_fd_sc_hd__nand2_1 _0864_ (
    .A(\alu_inst.b_i [0]),
    .B(\alu_inst.a_i [7]),
    .Y(_0271_)
  );
  sky130_fd_sc_hd__and2_0 _0865_ (
    .A(_0228_),
    .B(_0271_),
    .X(_0272_)
  );
  sky130_fd_sc_hd__nor2_1 _0866_ (
    .A(_0228_),
    .B(_0271_),
    .Y(_0273_)
  );
  sky130_fd_sc_hd__o21a_1 _0867_ (
    .A1(_0272_),
    .A2(_0273_),
    .B1(_0270_),
    .X(_0274_)
  );
  sky130_fd_sc_hd__nor3_1 _0868_ (
    .A(_0270_),
    .B(_0272_),
    .C(_0273_),
    .Y(_0276_)
  );
  sky130_fd_sc_hd__nor2_1 _0869_ (
    .A(_0274_),
    .B(_0276_),
    .Y(_0277_)
  );
  sky130_fd_sc_hd__o21ai_0 _0870_ (
    .A1(_0229_),
    .A2(_0231_),
    .B1(_0277_),
    .Y(_0278_)
  );
  sky130_fd_sc_hd__nor3_1 _0871_ (
    .A(_0229_),
    .B(_0231_),
    .C(_0277_),
    .Y(_0279_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0872_ (
    .A(_0278_),
    .SLEEP(_0279_),
    .X(_0280_)
  );
  sky130_fd_sc_hd__nand2_1 _0873_ (
    .A(_0269_),
    .B(_0280_),
    .Y(_0281_)
  );
  sky130_fd_sc_hd__xor2_1 _0874_ (
    .A(_0269_),
    .B(_0280_),
    .X(_0282_)
  );
  sky130_fd_sc_hd__nand2b_1 _0875_ (
    .A_N(_0262_),
    .B(_0282_),
    .Y(_0283_)
  );
  sky130_fd_sc_hd__xnor2_1 _0876_ (
    .A(_0262_),
    .B(_0282_),
    .Y(_0284_)
  );
  sky130_fd_sc_hd__nand2_1 _0877_ (
    .A(_0261_),
    .B(_0284_),
    .Y(_0285_)
  );
  sky130_fd_sc_hd__xnor2_1 _0878_ (
    .A(_0261_),
    .B(_0284_),
    .Y(_0287_)
  );
  sky130_fd_sc_hd__nor2_1 _0879_ (
    .A(_0255_),
    .B(_0287_),
    .Y(_0288_)
  );
  sky130_fd_sc_hd__xor2_1 _0880_ (
    .A(_0255_),
    .B(_0287_),
    .X(_0289_)
  );
  sky130_fd_sc_hd__nor2_1 _0881_ (
    .A(_0218_),
    .B(_0289_),
    .Y(_0290_)
  );
  sky130_fd_sc_hd__and2_0 _0882_ (
    .A(_0218_),
    .B(_0289_),
    .X(_0291_)
  );
  sky130_fd_sc_hd__nor2_1 _0883_ (
    .A(_0290_),
    .B(_0291_),
    .Y(_0292_)
  );
  sky130_fd_sc_hd__nand2_1 _0884_ (
    .A(_0238_),
    .B(_0292_),
    .Y(_0293_)
  );
  sky130_fd_sc_hd__xnor2_1 _0885_ (
    .A(_0238_),
    .B(_0292_),
    .Y(_0294_)
  );
  sky130_fd_sc_hd__nand3_1 _0886_ (
    .A(_0240_),
    .B(_0242_),
    .C(_0294_),
    .Y(_0295_)
  );
  sky130_fd_sc_hd__a21o_1 _0887_ (
    .A1(_0240_),
    .A2(_0242_),
    .B1(_0294_),
    .X(_0296_)
  );
  sky130_fd_sc_hd__nand2_1 _0888_ (
    .A(_0295_),
    .B(_0296_),
    .Y(_0298_)
  );
  sky130_fd_sc_hd__nand2b_1 _0889_ (
    .A_N(\alu_inst.b_i [7]),
    .B(\alu_inst.a_i [7]),
    .Y(_0299_)
  );
  sky130_fd_sc_hd__nand2b_1 _0890_ (
    .A_N(_0104_),
    .B(_0299_),
    .Y(_0300_)
  );
  sky130_fd_sc_hd__maj3_1 _0891_ (
    .A(\alu_inst.a_i [6]),
    .B(\alu_inst.b_i [6]),
    .C(_0248_),
    .X(_0301_)
  );
  sky130_fd_sc_hd__nand2_1 _0892_ (
    .A(_0300_),
    .B(_0301_),
    .Y(_0302_)
  );
  sky130_fd_sc_hd__o21a_1 _0893_ (
    .A1(_0300_),
    .A2(_0301_),
    .B1(_0117_),
    .X(_0303_)
  );
  sky130_fd_sc_hd__nand3_1 _0894_ (
    .A(_0245_),
    .B(_0251_),
    .C(_0300_),
    .Y(_0304_)
  );
  sky130_fd_sc_hd__a21oi_1 _0895_ (
    .A1(_0245_),
    .A2(_0251_),
    .B1(_0300_),
    .Y(_0305_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0896_ (
    .A(_0113_),
    .SLEEP(_0305_),
    .X(_0306_)
  );
  sky130_fd_sc_hd__nand2_1 _0897_ (
    .A(_0304_),
    .B(_0306_),
    .Y(_0307_)
  );
  sky130_fd_sc_hd__nand3_1 _0898_ (
    .A(\alu_inst.op_i [1]),
    .B(\alu_inst.op_i [0]),
    .C(_0383_),
    .Y(_0309_)
  );
  sky130_fd_sc_hd__nor2_1 _0899_ (
    .A(_0254_),
    .B(\alu_inst.a_i [7]),
    .Y(_0310_)
  );
  sky130_fd_sc_hd__nor2_1 _0900_ (
    .A(\alu_inst.b_i [0]),
    .B(_0309_),
    .Y(_0311_)
  );
  sky130_fd_sc_hd__o21ai_0 _0901_ (
    .A1(_0309_),
    .A2(_0310_),
    .B1(_0307_),
    .Y(_0312_)
  );
  sky130_fd_sc_hd__a21oi_1 _0902_ (
    .A1(_0302_),
    .A2(_0303_),
    .B1(_0312_),
    .Y(_0313_)
  );
  sky130_fd_sc_hd__o21ai_0 _0903_ (
    .A1(_0107_),
    .A2(_0298_),
    .B1(_0313_),
    .Y(\alu_inst.r_o [7])
  );
  sky130_fd_sc_hd__nand2_1 _0904_ (
    .A(\alu_inst.b_i [7]),
    .B(_0100_),
    .Y(_0314_)
  );
  sky130_fd_sc_hd__nand2_1 _0905_ (
    .A(_0302_),
    .B(_0314_),
    .Y(_0315_)
  );
  sky130_fd_sc_hd__nand2_1 _0906_ (
    .A(_0117_),
    .B(_0315_),
    .Y(_0316_)
  );
  sky130_fd_sc_hd__a31oi_1 _0907_ (
    .A1(\alu_inst.b_i [6]),
    .A2(\alu_inst.a_i [1]),
    .A3(_0258_),
    .B1(_0260_),
    .Y(_0317_)
  );
  sky130_fd_sc_hd__nand2_1 _0908_ (
    .A(\alu_inst.b_i [7]),
    .B(\alu_inst.a_i [1]),
    .Y(_0319_)
  );
  sky130_fd_sc_hd__nand2_1 _0909_ (
    .A(\alu_inst.a_i [2]),
    .B(\alu_inst.b_i [6]),
    .Y(_0320_)
  );
  sky130_fd_sc_hd__o21ai_0 _0910_ (
    .A1(_0177_),
    .A2(_0205_),
    .B1(_0268_),
    .Y(_0321_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0911_ (
    .A(_0321_),
    .SLEEP(_0320_),
    .X(_0322_)
  );
  sky130_fd_sc_hd__xor2_1 _0912_ (
    .A(_0320_),
    .B(_0321_),
    .X(_0323_)
  );
  sky130_fd_sc_hd__nor2_1 _0913_ (
    .A(_0319_),
    .B(_0323_),
    .Y(_0324_)
  );
  sky130_fd_sc_hd__xor2_1 _0914_ (
    .A(_0319_),
    .B(_0323_),
    .X(_0325_)
  );
  sky130_fd_sc_hd__nand2_1 _0915_ (
    .A(\alu_inst.a_i [3]),
    .B(\alu_inst.b_i [5]),
    .Y(_0326_)
  );
  sky130_fd_sc_hd__nand2_1 _0916_ (
    .A(\alu_inst.a_i [5]),
    .B(\alu_inst.b_i [3]),
    .Y(_0327_)
  );
  sky130_fd_sc_hd__xor2_1 _0917_ (
    .A(_0205_),
    .B(_0327_),
    .X(_0328_)
  );
  sky130_fd_sc_hd__xnor2_1 _0918_ (
    .A(_0326_),
    .B(_0328_),
    .Y(_0330_)
  );
  sky130_fd_sc_hd__a22oi_1 _0919_ (
    .A1(\alu_inst.a_i [7]),
    .A2(\alu_inst.b_i [1]),
    .B1(\alu_inst.b_i [2]),
    .B2(\alu_inst.a_i [6]),
    .Y(_0331_)
  );
  sky130_fd_sc_hd__nand4_1 _0920_ (
    .A(\alu_inst.a_i [7]),
    .B(\alu_inst.a_i [6]),
    .C(\alu_inst.b_i [1]),
    .D(\alu_inst.b_i [2]),
    .Y(_0332_)
  );
  sky130_fd_sc_hd__nor2b_1 _0921_ (
    .A(_0331_),
    .B_N(_0332_),
    .Y(_0333_)
  );
  sky130_fd_sc_hd__o21a_1 _0922_ (
    .A1(_0273_),
    .A2(_0276_),
    .B1(_0333_),
    .X(_0334_)
  );
  sky130_fd_sc_hd__nor3_1 _0923_ (
    .A(_0273_),
    .B(_0276_),
    .C(_0333_),
    .Y(_0335_)
  );
  sky130_fd_sc_hd__nor2_1 _0924_ (
    .A(_0334_),
    .B(_0335_),
    .Y(_0336_)
  );
  sky130_fd_sc_hd__xnor2_1 _0925_ (
    .A(_0330_),
    .B(_0336_),
    .Y(_0337_)
  );
  sky130_fd_sc_hd__a21oi_1 _0926_ (
    .A1(_0278_),
    .A2(_0281_),
    .B1(_0337_),
    .Y(_0338_)
  );
  sky130_fd_sc_hd__and3_1 _0927_ (
    .A(_0278_),
    .B(_0281_),
    .C(_0337_),
    .X(_0339_)
  );
  sky130_fd_sc_hd__nor2_1 _0928_ (
    .A(_0338_),
    .B(_0339_),
    .Y(_0341_)
  );
  sky130_fd_sc_hd__and2_0 _0929_ (
    .A(_0325_),
    .B(_0341_),
    .X(_0342_)
  );
  sky130_fd_sc_hd__xnor2_1 _0930_ (
    .A(_0325_),
    .B(_0341_),
    .Y(_0343_)
  );
  sky130_fd_sc_hd__a21oi_1 _0931_ (
    .A1(_0283_),
    .A2(_0285_),
    .B1(_0343_),
    .Y(_0344_)
  );
  sky130_fd_sc_hd__and3_1 _0932_ (
    .A(_0283_),
    .B(_0285_),
    .C(_0343_),
    .X(_0345_)
  );
  sky130_fd_sc_hd__nor2_1 _0933_ (
    .A(_0344_),
    .B(_0345_),
    .Y(_0346_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0934_ (
    .A(_0346_),
    .SLEEP(_0317_),
    .X(_0347_)
  );
  sky130_fd_sc_hd__xnor2_1 _0935_ (
    .A(_0317_),
    .B(_0346_),
    .Y(_0348_)
  );
  sky130_fd_sc_hd__o21ai_0 _0936_ (
    .A1(_0288_),
    .A2(_0291_),
    .B1(_0348_),
    .Y(_0349_)
  );
  sky130_fd_sc_hd__or3_1 _0937_ (
    .A(_0288_),
    .B(_0291_),
    .C(_0348_),
    .X(_0350_)
  );
  sky130_fd_sc_hd__nand2_1 _0938_ (
    .A(_0349_),
    .B(_0350_),
    .Y(_0352_)
  );
  sky130_fd_sc_hd__a21o_1 _0939_ (
    .A1(_0293_),
    .A2(_0296_),
    .B1(_0352_),
    .X(_0353_)
  );
  sky130_fd_sc_hd__nand3_1 _0940_ (
    .A(_0293_),
    .B(_0296_),
    .C(_0352_),
    .Y(_0354_)
  );
  sky130_fd_sc_hd__nand3_1 _0941_ (
    .A(_0106_),
    .B(_0353_),
    .C(_0354_),
    .Y(_0355_)
  );
  sky130_fd_sc_hd__a21oi_1 _0942_ (
    .A1(_0299_),
    .A2(_0306_),
    .B1(_0311_),
    .Y(_0356_)
  );
  sky130_fd_sc_hd__nand3_1 _0943_ (
    .A(_0316_),
    .B(_0355_),
    .C(_0356_),
    .Y(\alu_inst.r_o [8])
  );
  sky130_fd_sc_hd__nor2_1 _0944_ (
    .A(_0344_),
    .B(_0347_),
    .Y(_0357_)
  );
  sky130_fd_sc_hd__nand2_1 _0945_ (
    .A(\alu_inst.a_i [2]),
    .B(\alu_inst.b_i [7]),
    .Y(_0358_)
  );
  sky130_fd_sc_hd__nand2_1 _0946_ (
    .A(\alu_inst.a_i [3]),
    .B(\alu_inst.b_i [6]),
    .Y(_0359_)
  );
  sky130_fd_sc_hd__maj3_1 _0947_ (
    .A(_0205_),
    .B(_0326_),
    .C(_0327_),
    .X(_0360_)
  );
  sky130_fd_sc_hd__xnor2_1 _0948_ (
    .A(_0359_),
    .B(_0360_),
    .Y(_0362_)
  );
  sky130_fd_sc_hd__xnor2_1 _0949_ (
    .A(_0358_),
    .B(_0362_),
    .Y(_0363_)
  );
  sky130_fd_sc_hd__a21oi_1 _0950_ (
    .A1(_0330_),
    .A2(_0336_),
    .B1(_0334_),
    .Y(_0364_)
  );
  sky130_fd_sc_hd__nand2_1 _0951_ (
    .A(\alu_inst.a_i [4]),
    .B(\alu_inst.b_i [5]),
    .Y(_0365_)
  );
  sky130_fd_sc_hd__a22oi_1 _0952_ (
    .A1(\alu_inst.a_i [5]),
    .A2(\alu_inst.b_i [4]),
    .B1(\alu_inst.b_i [3]),
    .B2(\alu_inst.a_i [6]),
    .Y(_0366_)
  );
  sky130_fd_sc_hd__nand2_1 _0953_ (
    .A(\alu_inst.a_i [6]),
    .B(\alu_inst.b_i [4]),
    .Y(_0367_)
  );
  sky130_fd_sc_hd__nor2_1 _0954_ (
    .A(_0327_),
    .B(_0367_),
    .Y(_0368_)
  );
  sky130_fd_sc_hd__nor2_1 _0955_ (
    .A(_0366_),
    .B(_0368_),
    .Y(_0369_)
  );
  sky130_fd_sc_hd__xor2_1 _0956_ (
    .A(_0365_),
    .B(_0369_),
    .X(_0370_)
  );
  sky130_fd_sc_hd__nand3_1 _0957_ (
    .A(\alu_inst.b_i [2]),
    .B(_0425_),
    .C(_0332_),
    .Y(_0371_)
  );
  sky130_fd_sc_hd__xnor2_1 _0958_ (
    .A(_0370_),
    .B(_0371_),
    .Y(_0373_)
  );
  sky130_fd_sc_hd__xnor2_1 _0959_ (
    .A(_0364_),
    .B(_0373_),
    .Y(_0374_)
  );
  sky130_fd_sc_hd__xor2_1 _0960_ (
    .A(_0363_),
    .B(_0374_),
    .X(_0375_)
  );
  sky130_fd_sc_hd__o21ai_0 _0961_ (
    .A1(_0338_),
    .A2(_0342_),
    .B1(_0375_),
    .Y(_0376_)
  );
  sky130_fd_sc_hd__nor3_1 _0962_ (
    .A(_0338_),
    .B(_0342_),
    .C(_0375_),
    .Y(_0377_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0963_ (
    .A(_0376_),
    .SLEEP(_0377_),
    .X(_0378_)
  );
  sky130_fd_sc_hd__o21ai_0 _0964_ (
    .A1(_0322_),
    .A2(_0324_),
    .B1(_0378_),
    .Y(_0379_)
  );
  sky130_fd_sc_hd__nor3_1 _0965_ (
    .A(_0322_),
    .B(_0324_),
    .C(_0378_),
    .Y(_0380_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0966_ (
    .A(_0379_),
    .SLEEP(_0380_),
    .X(_0381_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0967_ (
    .A(_0381_),
    .SLEEP(_0357_),
    .X(_0382_)
  );
  sky130_fd_sc_hd__xor2_1 _0968_ (
    .A(_0357_),
    .B(_0381_),
    .X(_0384_)
  );
  sky130_fd_sc_hd__nand3_1 _0969_ (
    .A(_0349_),
    .B(_0353_),
    .C(_0384_),
    .Y(_0385_)
  );
  sky130_fd_sc_hd__a21oi_1 _0970_ (
    .A1(_0349_),
    .A2(_0353_),
    .B1(_0384_),
    .Y(_0386_)
  );
  sky130_fd_sc_hd__nand2_1 _0971_ (
    .A(_0106_),
    .B(_0385_),
    .Y(_0387_)
  );
  sky130_fd_sc_hd__o21ai_0 _0972_ (
    .A1(_0386_),
    .A2(_0387_),
    .B1(_0356_),
    .Y(\alu_inst.r_o [9])
  );
  sky130_fd_sc_hd__maj3_1 _0973_ (
    .A(_0358_),
    .B(_0359_),
    .C(_0360_),
    .X(_0388_)
  );
  sky130_fd_sc_hd__maj3_1 _0974_ (
    .A(_0363_),
    .B(_0364_),
    .C(_0373_),
    .X(_0389_)
  );
  sky130_fd_sc_hd__nand2_1 _0975_ (
    .A(\alu_inst.a_i [3]),
    .B(\alu_inst.b_i [7]),
    .Y(_0390_)
  );
  sky130_fd_sc_hd__nand2_1 _0976_ (
    .A(\alu_inst.a_i [4]),
    .B(\alu_inst.b_i [6]),
    .Y(_0391_)
  );
  sky130_fd_sc_hd__a31oi_1 _0977_ (
    .A1(\alu_inst.a_i [4]),
    .A2(\alu_inst.b_i [5]),
    .A3(_0369_),
    .B1(_0368_),
    .Y(_0392_)
  );
  sky130_fd_sc_hd__xnor2_1 _0978_ (
    .A(_0391_),
    .B(_0392_),
    .Y(_0394_)
  );
  sky130_fd_sc_hd__xor2_1 _0979_ (
    .A(_0390_),
    .B(_0394_),
    .X(_0395_)
  );
  sky130_fd_sc_hd__o21a_1 _0980_ (
    .A1(_0370_),
    .A2(_0371_),
    .B1(_0332_),
    .X(_0396_)
  );
  sky130_fd_sc_hd__nand2_1 _0981_ (
    .A(\alu_inst.b_i [3]),
    .B(_0485_),
    .Y(_0397_)
  );
  sky130_fd_sc_hd__xnor2_1 _0982_ (
    .A(_0367_),
    .B(_0397_),
    .Y(_0398_)
  );
  sky130_fd_sc_hd__xnor2_1 _0983_ (
    .A(_0247_),
    .B(_0398_),
    .Y(_0399_)
  );
  sky130_fd_sc_hd__nor2_1 _0984_ (
    .A(_0396_),
    .B(_0399_),
    .Y(_0400_)
  );
  sky130_fd_sc_hd__xor2_1 _0985_ (
    .A(_0396_),
    .B(_0399_),
    .X(_0401_)
  );
  sky130_fd_sc_hd__xnor2_1 _0986_ (
    .A(_0395_),
    .B(_0401_),
    .Y(_0402_)
  );
  sky130_fd_sc_hd__xor2_1 _0987_ (
    .A(_0389_),
    .B(_0402_),
    .X(_0403_)
  );
  sky130_fd_sc_hd__xor2_1 _0988_ (
    .A(_0388_),
    .B(_0403_),
    .X(_0405_)
  );
  sky130_fd_sc_hd__a21oi_1 _0989_ (
    .A1(_0376_),
    .A2(_0379_),
    .B1(_0405_),
    .Y(_0406_)
  );
  sky130_fd_sc_hd__and3_1 _0990_ (
    .A(_0376_),
    .B(_0379_),
    .C(_0405_),
    .X(_0407_)
  );
  sky130_fd_sc_hd__nor2_1 _0991_ (
    .A(_0406_),
    .B(_0407_),
    .Y(_0408_)
  );
  sky130_fd_sc_hd__o21a_1 _0992_ (
    .A1(_0382_),
    .A2(_0386_),
    .B1(_0408_),
    .X(_0409_)
  );
  sky130_fd_sc_hd__o31ai_1 _0993_ (
    .A1(_0382_),
    .A2(_0386_),
    .A3(_0408_),
    .B1(_0106_),
    .Y(_0410_)
  );
  sky130_fd_sc_hd__o21ai_0 _0994_ (
    .A1(_0409_),
    .A2(_0410_),
    .B1(_0356_),
    .Y(\alu_inst.r_o [10])
  );
  sky130_fd_sc_hd__maj3_1 _0995_ (
    .A(_0388_),
    .B(_0389_),
    .C(_0402_),
    .X(_0411_)
  );
  sky130_fd_sc_hd__maj3_1 _0996_ (
    .A(_0390_),
    .B(_0391_),
    .C(_0392_),
    .X(_0412_)
  );
  sky130_fd_sc_hd__a21oi_1 _0997_ (
    .A1(_0395_),
    .A2(_0401_),
    .B1(_0400_),
    .Y(_0413_)
  );
  sky130_fd_sc_hd__nand2_1 _0998_ (
    .A(\alu_inst.a_i [4]),
    .B(\alu_inst.b_i [7]),
    .Y(_0415_)
  );
  sky130_fd_sc_hd__nand2_1 _0999_ (
    .A(\alu_inst.a_i [5]),
    .B(\alu_inst.b_i [6]),
    .Y(_0416_)
  );
  sky130_fd_sc_hd__maj3_1 _1000_ (
    .A(_0247_),
    .B(_0367_),
    .C(_0397_),
    .X(_0417_)
  );
  sky130_fd_sc_hd__xnor2_1 _1001_ (
    .A(_0416_),
    .B(_0417_),
    .Y(_0418_)
  );
  sky130_fd_sc_hd__xor2_1 _1002_ (
    .A(_0415_),
    .B(_0418_),
    .X(_0419_)
  );
  sky130_fd_sc_hd__and3_1 _1003_ (
    .A(\alu_inst.b_i [4]),
    .B(_0485_),
    .C(_0499_),
    .X(_0420_)
  );
  sky130_fd_sc_hd__a21oi_1 _1004_ (
    .A1(\alu_inst.a_i [6]),
    .A2(\alu_inst.b_i [5]),
    .B1(_0420_),
    .Y(_0421_)
  );
  sky130_fd_sc_hd__and3_1 _1005_ (
    .A(\alu_inst.a_i [6]),
    .B(\alu_inst.b_i [5]),
    .C(_0420_),
    .X(_0422_)
  );
  sky130_fd_sc_hd__nor2_1 _1006_ (
    .A(_0421_),
    .B(_0422_),
    .Y(_0423_)
  );
  sky130_fd_sc_hd__nand2_1 _1007_ (
    .A(_0419_),
    .B(_0423_),
    .Y(_0424_)
  );
  sky130_fd_sc_hd__xnor2_1 _1008_ (
    .A(_0419_),
    .B(_0423_),
    .Y(_0426_)
  );
  sky130_fd_sc_hd__xor3_1 _1009_ (
    .A(_0412_),
    .B(_0413_),
    .C(_0426_),
    .X(_0427_)
  );
  sky130_fd_sc_hd__nor2_1 _1010_ (
    .A(_0411_),
    .B(_0427_),
    .Y(_0428_)
  );
  sky130_fd_sc_hd__xor2_1 _1011_ (
    .A(_0411_),
    .B(_0427_),
    .X(_0429_)
  );
  sky130_fd_sc_hd__o21a_1 _1012_ (
    .A1(_0406_),
    .A2(_0409_),
    .B1(_0429_),
    .X(_0430_)
  );
  sky130_fd_sc_hd__o31ai_1 _1013_ (
    .A1(_0406_),
    .A2(_0409_),
    .A3(_0429_),
    .B1(_0106_),
    .Y(_0431_)
  );
  sky130_fd_sc_hd__o21ai_0 _1014_ (
    .A1(_0430_),
    .A2(_0431_),
    .B1(_0356_),
    .Y(\alu_inst.r_o [11])
  );
  sky130_fd_sc_hd__nor2_1 _1015_ (
    .A(_0428_),
    .B(_0430_),
    .Y(_0432_)
  );
  sky130_fd_sc_hd__maj3_1 _1016_ (
    .A(_0412_),
    .B(_0413_),
    .C(_0426_),
    .X(_0433_)
  );
  sky130_fd_sc_hd__maj3_1 _1017_ (
    .A(_0415_),
    .B(_0416_),
    .C(_0417_),
    .X(_0434_)
  );
  sky130_fd_sc_hd__nand2_1 _1018_ (
    .A(\alu_inst.b_i [5]),
    .B(_0003_),
    .Y(_0436_)
  );
  sky130_fd_sc_hd__nand2_1 _1019_ (
    .A(\alu_inst.a_i [5]),
    .B(\alu_inst.b_i [7]),
    .Y(_0437_)
  );
  sky130_fd_sc_hd__a21oi_1 _1020_ (
    .A1(\alu_inst.a_i [6]),
    .A2(\alu_inst.b_i [6]),
    .B1(_0422_),
    .Y(_0438_)
  );
  sky130_fd_sc_hd__a21o_1 _1021_ (
    .A1(\alu_inst.b_i [6]),
    .A2(_0422_),
    .B1(_0438_),
    .X(_0439_)
  );
  sky130_fd_sc_hd__nor2_1 _1022_ (
    .A(_0437_),
    .B(_0439_),
    .Y(_0440_)
  );
  sky130_fd_sc_hd__xor2_1 _1023_ (
    .A(_0437_),
    .B(_0439_),
    .X(_0441_)
  );
  sky130_fd_sc_hd__nand3_1 _1024_ (
    .A(\alu_inst.b_i [5]),
    .B(_0003_),
    .C(_0441_),
    .Y(_0442_)
  );
  sky130_fd_sc_hd__xnor2_1 _1025_ (
    .A(_0436_),
    .B(_0441_),
    .Y(_0443_)
  );
  sky130_fd_sc_hd__xnor2_1 _1026_ (
    .A(_0424_),
    .B(_0443_),
    .Y(_0444_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1027_ (
    .A(_0444_),
    .SLEEP(_0434_),
    .X(_0445_)
  );
  sky130_fd_sc_hd__xnor2_1 _1028_ (
    .A(_0434_),
    .B(_0444_),
    .Y(_0447_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1029_ (
    .A(_0447_),
    .SLEEP(_0433_),
    .X(_0448_)
  );
  sky130_fd_sc_hd__xor2_1 _1030_ (
    .A(_0433_),
    .B(_0447_),
    .X(_0449_)
  );
  sky130_fd_sc_hd__nand2_1 _1031_ (
    .A(_0432_),
    .B(_0449_),
    .Y(_0450_)
  );
  sky130_fd_sc_hd__nor2_1 _1032_ (
    .A(_0432_),
    .B(_0449_),
    .Y(_0451_)
  );
  sky130_fd_sc_hd__nand2_1 _1033_ (
    .A(_0106_),
    .B(_0450_),
    .Y(_0452_)
  );
  sky130_fd_sc_hd__o21ai_0 _1034_ (
    .A1(_0451_),
    .A2(_0452_),
    .B1(_0356_),
    .Y(\alu_inst.r_o [12])
  );
  sky130_fd_sc_hd__nor2_1 _1035_ (
    .A(_0448_),
    .B(_0451_),
    .Y(_0453_)
  );
  sky130_fd_sc_hd__a31oi_1 _1036_ (
    .A1(_0419_),
    .A2(_0423_),
    .A3(_0443_),
    .B1(_0445_),
    .Y(_0454_)
  );
  sky130_fd_sc_hd__a21oi_1 _1037_ (
    .A1(\alu_inst.b_i [6]),
    .A2(_0422_),
    .B1(_0440_),
    .Y(_0455_)
  );
  sky130_fd_sc_hd__and3_1 _1038_ (
    .A(\alu_inst.b_i [6]),
    .B(_0003_),
    .C(_0067_),
    .X(_0457_)
  );
  sky130_fd_sc_hd__a21oi_1 _1039_ (
    .A1(\alu_inst.a_i [6]),
    .A2(\alu_inst.b_i [7]),
    .B1(_0457_),
    .Y(_0458_)
  );
  sky130_fd_sc_hd__and3_1 _1040_ (
    .A(\alu_inst.a_i [6]),
    .B(\alu_inst.b_i [7]),
    .C(_0457_),
    .X(_0459_)
  );
  sky130_fd_sc_hd__nor2_1 _1041_ (
    .A(_0458_),
    .B(_0459_),
    .Y(_0460_)
  );
  sky130_fd_sc_hd__xor2_1 _1042_ (
    .A(_0442_),
    .B(_0460_),
    .X(_0461_)
  );
  sky130_fd_sc_hd__nor2_1 _1043_ (
    .A(_0455_),
    .B(_0461_),
    .Y(_0462_)
  );
  sky130_fd_sc_hd__xor2_1 _1044_ (
    .A(_0455_),
    .B(_0461_),
    .X(_0463_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1045_ (
    .A(_0463_),
    .SLEEP(_0454_),
    .X(_0464_)
  );
  sky130_fd_sc_hd__xor2_1 _1046_ (
    .A(_0454_),
    .B(_0463_),
    .X(_0465_)
  );
  sky130_fd_sc_hd__nand2_1 _1047_ (
    .A(_0453_),
    .B(_0465_),
    .Y(_0466_)
  );
  sky130_fd_sc_hd__nor2_1 _1048_ (
    .A(_0453_),
    .B(_0465_),
    .Y(_0468_)
  );
  sky130_fd_sc_hd__nand2_1 _1049_ (
    .A(_0106_),
    .B(_0466_),
    .Y(_0469_)
  );
  sky130_fd_sc_hd__o21ai_0 _1050_ (
    .A1(_0468_),
    .A2(_0469_),
    .B1(_0356_),
    .Y(\alu_inst.r_o [13])
  );
  sky130_fd_sc_hd__nor2_1 _1051_ (
    .A(_0464_),
    .B(_0468_),
    .Y(_0470_)
  );
  sky130_fd_sc_hd__a41oi_1 _1052_ (
    .A1(\alu_inst.b_i [5]),
    .A2(_0003_),
    .A3(_0441_),
    .A4(_0460_),
    .B1(_0462_),
    .Y(_0471_)
  );
  sky130_fd_sc_hd__nor2_1 _1053_ (
    .A(_0314_),
    .B(_0459_),
    .Y(_0472_)
  );
  sky130_fd_sc_hd__xor2_1 _1054_ (
    .A(_0471_),
    .B(_0472_),
    .X(_0473_)
  );
  sky130_fd_sc_hd__nand2_1 _1055_ (
    .A(_0470_),
    .B(_0473_),
    .Y(_0474_)
  );
  sky130_fd_sc_hd__nor2_1 _1056_ (
    .A(_0470_),
    .B(_0473_),
    .Y(_0475_)
  );
  sky130_fd_sc_hd__nand2_1 _1057_ (
    .A(_0106_),
    .B(_0474_),
    .Y(_0476_)
  );
  sky130_fd_sc_hd__o21ai_0 _1058_ (
    .A1(_0475_),
    .A2(_0476_),
    .B1(_0356_),
    .Y(\alu_inst.r_o [14])
  );
  sky130_fd_sc_hd__o21bai_1 _1059_ (
    .A1(_0314_),
    .A2(_0471_),
    .B1_N(_0459_),
    .Y(_0478_)
  );
  sky130_fd_sc_hd__o21ai_0 _1060_ (
    .A1(_0475_),
    .A2(_0478_),
    .B1(_0106_),
    .Y(_0479_)
  );
  sky130_fd_sc_hd__nand2_1 _1061_ (
    .A(_0356_),
    .B(_0479_),
    .Y(\alu_inst.r_o [15])
  );
  assign \alu_inst.a_i  = a_i;
  assign \alu_inst.b_i  = b_i;
  assign \alu_inst.op_i  = op_i;
  assign r_o = \alu_inst.r_o ;
endmodule
