/* Generated by Yosys 0.9+4274 (git sha1 e6dd4db0, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "../project_template.v:1.1-5.10" *)
module project_template(a, b, c);
  (* src = "../project_template.v:2.14-2.15" *)
  input a;
  (* src = "../project_template.v:2.16-2.17" *)
  input b;
  (* src = "../project_template.v:3.15-3.16" *)
  output c;
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0_ (
    .A(b),
    .SLEEP(a),
    .X(c)
  );
endmodule
