/* Generated by Yosys 0.9+4274 (git sha1 e6dd4db0, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "../trianglewave.v:1.1-55.10" *)
module trianglewave(clk, rst_n, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "../trianglewave.v:4.14-4.17" *)
  input clk;
  (* src = "../trianglewave.v:5.31-5.36" *)
  output [2:0] count;
  (* src = "../trianglewave.v:7.24-7.34" *)
  wire [2:0] count_next;
  (* src = "../trianglewave.v:8.12-8.16" *)
  wire down;
  (* src = "../trianglewave.v:8.18-8.27" *)
  wire down_next;
  (* src = "../trianglewave.v:4.18-4.23" *)
  input rst_n;
  sky130_fd_sc_hd__clkinv_1 _05_ (
    .A(count[0]),
    .Y(count_next[0])
  );
  sky130_fd_sc_hd__and3b_1 _06_ (
    .A_N(count[0]),
    .B(count[1]),
    .C(count[2]),
    .X(_00_)
  );
  sky130_fd_sc_hd__nor2_1 _07_ (
    .A(count[1]),
    .B(count[2]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _08_ (
    .A1_N(down),
    .A2_N(_00_),
    .B1(_01_),
    .B2(count[0]),
    .Y(down_next)
  );
  sky130_fd_sc_hd__xor2_1 _09_ (
    .A(count[1]),
    .B(down),
    .X(_02_)
  );
  sky130_fd_sc_hd__xnor2_1 _10_ (
    .A(count_next[0]),
    .B(_02_),
    .Y(count_next[1])
  );
  sky130_fd_sc_hd__maj3_1 _11_ (
    .A(count[0]),
    .B(count[1]),
    .C(down),
    .X(_03_)
  );
  sky130_fd_sc_hd__xnor2_1 _12_ (
    .A(count[2]),
    .B(down),
    .Y(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _13_ (
    .A(_03_),
    .B(_04_),
    .Y(count_next[2])
  );
  (* src = "../trianglewave.v:26.8-32.18" *)
  sky130_fd_sc_hd__dfrtp_1 _14_ (
    .CLK(clk),
    .D(down_next),
    .Q(down),
    .RESET_B(rst_n)
  );
  (* src = "../trianglewave.v:10.8-16.18" *)
  sky130_fd_sc_hd__dfrtp_1 _15_ (
    .CLK(clk),
    .D(count_next[0]),
    .Q(count[0]),
    .RESET_B(rst_n)
  );
  (* src = "../trianglewave.v:10.8-16.18" *)
  sky130_fd_sc_hd__dfrtp_1 _16_ (
    .CLK(clk),
    .D(count_next[1]),
    .Q(count[1]),
    .RESET_B(rst_n)
  );
  (* src = "../trianglewave.v:10.8-16.18" *)
  sky130_fd_sc_hd__dfrtp_1 _17_ (
    .CLK(clk),
    .D(count_next[2]),
    .Q(count[2]),
    .RESET_B(rst_n)
  );
endmodule
