/* Generated by Yosys 0.9+4081 (git sha1 862e84eb, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

module top(clk, rst_n, s_i, p_o);
  input clk;
  output [7:0] p_o;
  input rst_n;
  input s_i;
  wire \shiftreg_inst.clk ;
  wire [7:0] \shiftreg_inst.p_next ;
  wire [7:0] \shiftreg_inst.p_o ;
  wire \shiftreg_inst.rst_n ;
  wire \shiftreg_inst.s_i ;
  sky130_fd_sc_hd__dfrtp_1 _0_ (
    .CLK(\shiftreg_inst.clk ),
    .D(\shiftreg_inst.p_o [1]),
    .Q(\shiftreg_inst.p_o [0]),
    .RESET_B(\shiftreg_inst.rst_n )
  );
  sky130_fd_sc_hd__dfrtp_1 _1_ (
    .CLK(\shiftreg_inst.clk ),
    .D(\shiftreg_inst.p_o [2]),
    .Q(\shiftreg_inst.p_o [1]),
    .RESET_B(\shiftreg_inst.rst_n )
  );
  sky130_fd_sc_hd__dfrtp_1 _2_ (
    .CLK(\shiftreg_inst.clk ),
    .D(\shiftreg_inst.p_o [3]),
    .Q(\shiftreg_inst.p_o [2]),
    .RESET_B(\shiftreg_inst.rst_n )
  );
  sky130_fd_sc_hd__dfrtp_1 _3_ (
    .CLK(\shiftreg_inst.clk ),
    .D(\shiftreg_inst.p_o [4]),
    .Q(\shiftreg_inst.p_o [3]),
    .RESET_B(\shiftreg_inst.rst_n )
  );
  sky130_fd_sc_hd__dfrtp_1 _4_ (
    .CLK(\shiftreg_inst.clk ),
    .D(\shiftreg_inst.p_o [5]),
    .Q(\shiftreg_inst.p_o [4]),
    .RESET_B(\shiftreg_inst.rst_n )
  );
  sky130_fd_sc_hd__dfrtp_1 _5_ (
    .CLK(\shiftreg_inst.clk ),
    .D(\shiftreg_inst.p_o [6]),
    .Q(\shiftreg_inst.p_o [5]),
    .RESET_B(\shiftreg_inst.rst_n )
  );
  sky130_fd_sc_hd__dfrtp_1 _6_ (
    .CLK(\shiftreg_inst.clk ),
    .D(\shiftreg_inst.p_o [7]),
    .Q(\shiftreg_inst.p_o [6]),
    .RESET_B(\shiftreg_inst.rst_n )
  );
  sky130_fd_sc_hd__dfrtp_1 _7_ (
    .CLK(\shiftreg_inst.clk ),
    .D(\shiftreg_inst.s_i ),
    .Q(\shiftreg_inst.p_o [7]),
    .RESET_B(\shiftreg_inst.rst_n )
  );
  assign \shiftreg_inst.p_next  = { \shiftreg_inst.s_i , \shiftreg_inst.p_o [7:1] };
  assign \shiftreg_inst.clk  = clk;
  assign p_o = \shiftreg_inst.p_o ;
  assign \shiftreg_inst.rst_n  = rst_n;
  assign \shiftreg_inst.s_i  = s_i;
endmodule
