/* Generated by Yosys 0.9+4081 (git sha1 862e84eb, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

module \$paramod\shiftreg\n=s32'00000000000000000000000000001000 (clk, rst_n, s_i, p_o);
  input clk;
  wire [7:0] p_next;
  output [7:0] p_o;
  input rst_n;
  input s_i;
  sky130_fd_sc_hd__dfrtp_1 _0_ (
    .CLK(clk),
    .D(p_o[1]),
    .Q(p_o[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _1_ (
    .CLK(clk),
    .D(p_o[2]),
    .Q(p_o[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _2_ (
    .CLK(clk),
    .D(p_o[3]),
    .Q(p_o[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _3_ (
    .CLK(clk),
    .D(p_o[4]),
    .Q(p_o[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _4_ (
    .CLK(clk),
    .D(p_o[5]),
    .Q(p_o[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _5_ (
    .CLK(clk),
    .D(p_o[6]),
    .Q(p_o[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _6_ (
    .CLK(clk),
    .D(p_o[7]),
    .Q(p_o[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _7_ (
    .CLK(clk),
    .D(s_i),
    .Q(p_o[7]),
    .RESET_B(rst_n)
  );
  assign p_next = { s_i, p_o[7:1] };
endmodule

module top(clk, rst_n, s_i, p_o);
  input clk;
  output [7:0] p_o;
  input rst_n;
  input s_i;
  \$paramod\shiftreg\n=s32'00000000000000000000000000001000  shiftreg_inst (
    .clk(clk),
    .p_o(p_o),
    .rst_n(rst_n),
    .s_i(s_i)
  );
endmodule
