* SPICE netlist generated by Yosys 0.9+4274 (git sha1 e6dd4db0, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os)

X0 sel c b a sky130_fd_sc_hd__mux2_1

************************
* end of SPICE netlist *
************************

