/* Generated by Yosys 0.9+4274 (git sha1 e6dd4db0, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "../2x1mux.v:1.1-16.10" *)
module mux2X1(a, b, sel, c);
  (* src = "../2x1mux.v:2.14-2.15" *)
  input a;
  (* src = "../2x1mux.v:2.16-2.17" *)
  input b;
  (* src = "../2x1mux.v:3.19-3.20" *)
  output c;
  (* src = "../2x1mux.v:2.18-2.21" *)
  input sel;
  sky130_fd_sc_hd__mux2_1 _0_ (
    .A0(a),
    .A1(b),
    .S(sel),
    .X(c)
  );
endmodule
