/* Generated by Yosys 0.9+4274 (git sha1 e6dd4db0, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

module mux2X1(a, b, sel, c);
  input a;
  input b;
  output c;
  input sel;
  sky130_fd_sc_hd__mux2_1 _0_ (
    .A0(a),
    .A1(b),
    .S(sel),
    .X(c)
  );
endmodule

module top(a, b, sel, c);
  input a;
  input b;
  output c;
  input sel;
  mux2X1 dut (
    .a(a),
    .b(b),
    .c(c),
    .sel(sel)
  );
endmodule
