/* Generated by Yosys 0.9+4081 (git sha1 862e84eb, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

module top(clk, rst_n, count_o);
  wire _00_;
  wire _01_;
  input clk;
  output [3:0] count_o;
  wire \counter_inst.clk ;
  wire [3:0] \counter_inst.count_next ;
  wire [3:0] \counter_inst.count_o ;
  wire \counter_inst.rst_n ;
  input rst_n;
  sky130_fd_sc_hd__clkinv_1 _02_ (
    .A(\counter_inst.count_o [0]),
    .Y(\counter_inst.count_next [0])
  );
  sky130_fd_sc_hd__xor2_1 _03_ (
    .A(\counter_inst.count_o [1]),
    .B(\counter_inst.count_o [0]),
    .X(\counter_inst.count_next [1])
  );
  sky130_fd_sc_hd__nand3_1 _04_ (
    .A(\counter_inst.count_o [1]),
    .B(\counter_inst.count_o [0]),
    .C(\counter_inst.count_o [2]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__a21oi_1 _05_ (
    .A1(\counter_inst.count_o [1]),
    .A2(\counter_inst.count_o [0]),
    .B1(\counter_inst.count_o [2]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _06_ (
    .A(_00_),
    .SLEEP(_01_),
    .X(\counter_inst.count_next [2])
  );
  sky130_fd_sc_hd__xnor2_1 _07_ (
    .A(\counter_inst.count_o [3]),
    .B(_00_),
    .Y(\counter_inst.count_next [3])
  );
  sky130_fd_sc_hd__dfrtp_1 _08_ (
    .CLK(\counter_inst.clk ),
    .D(\counter_inst.count_next [0]),
    .Q(\counter_inst.count_o [0]),
    .RESET_B(\counter_inst.rst_n )
  );
  sky130_fd_sc_hd__dfrtp_1 _09_ (
    .CLK(\counter_inst.clk ),
    .D(\counter_inst.count_next [1]),
    .Q(\counter_inst.count_o [1]),
    .RESET_B(\counter_inst.rst_n )
  );
  sky130_fd_sc_hd__dfrtp_1 _10_ (
    .CLK(\counter_inst.clk ),
    .D(\counter_inst.count_next [2]),
    .Q(\counter_inst.count_o [2]),
    .RESET_B(\counter_inst.rst_n )
  );
  sky130_fd_sc_hd__dfrtp_1 _11_ (
    .CLK(\counter_inst.clk ),
    .D(\counter_inst.count_next [3]),
    .Q(\counter_inst.count_o [3]),
    .RESET_B(\counter_inst.rst_n )
  );
  assign \counter_inst.clk  = clk;
  assign count_o = \counter_inst.count_o ;
  assign \counter_inst.rst_n  = rst_n;
endmodule
