/* Generated by Yosys 0.9+4274 (git sha1 e6dd4db0, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "../dff.v:1.1-34.10" *)
module dff(clk, rst_n, d, q_no_rst, q_syn_rst, q_asyn_rst);
  wire _0_;
  (* src = "../dff.v:2.14-2.17" *)
  input clk;
  (* src = "../dff.v:2.24-2.25" *)
  input d;
  (* src = "../dff.v:3.38-3.48" *)
  output q_asyn_rst;
  (* src = "../dff.v:3.19-3.27" *)
  output q_no_rst;
  (* src = "../dff.v:3.28-3.37" *)
  output q_syn_rst;
  (* src = "../dff.v:2.18-2.23" *)
  input rst_n;
  sky130_fd_sc_hd__and2_0 _1_ (
    .A(d),
    .B(rst_n),
    .X(_0_)
  );
  (* src = "../dff.v:6.8-9.18" *)
  sky130_fd_sc_hd__dfxtp_1 _2_ (
    .CLK(clk),
    .D(d),
    .Q(q_no_rst)
  );
  (* src = "../dff.v:21.8-27.18" *)
  sky130_fd_sc_hd__dfxtp_1 _3_ (
    .CLK(clk),
    .D(_0_),
    .Q(q_syn_rst)
  );
  (* src = "../dff.v:12.8-18.18" *)
  sky130_fd_sc_hd__dfrtp_1 _4_ (
    .CLK(clk),
    .D(d),
    .Q(q_asyn_rst),
    .RESET_B(rst_n)
  );
endmodule
