/* Generated by Yosys 0.9+4081 (git sha1 862e84eb, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

module top(clk, rst_n, d, q_no_rst, q_syn_rst, q_asyn_rst);
  wire _0_;
  input clk;
  input d;
  wire \dff_inst.clk ;
  wire \dff_inst.d ;
  wire \dff_inst.q_asyn_rst ;
  wire \dff_inst.q_no_rst ;
  wire \dff_inst.q_syn_rst ;
  wire \dff_inst.rst_n ;
  output q_asyn_rst;
  output q_no_rst;
  output q_syn_rst;
  input rst_n;
  sky130_fd_sc_hd__and2_0 _1_ (
    .A(\dff_inst.d ),
    .B(\dff_inst.rst_n ),
    .X(_0_)
  );
  sky130_fd_sc_hd__dfxtp_1 _2_ (
    .CLK(\dff_inst.clk ),
    .D(\dff_inst.d ),
    .Q(\dff_inst.q_no_rst )
  );
  sky130_fd_sc_hd__dfrtp_1 _3_ (
    .CLK(\dff_inst.clk ),
    .D(\dff_inst.d ),
    .Q(\dff_inst.q_asyn_rst ),
    .RESET_B(\dff_inst.rst_n )
  );
  sky130_fd_sc_hd__dfxtp_1 _4_ (
    .CLK(\dff_inst.clk ),
    .D(_0_),
    .Q(\dff_inst.q_syn_rst )
  );
  assign \dff_inst.clk  = clk;
  assign \dff_inst.d  = d;
  assign q_asyn_rst = \dff_inst.q_asyn_rst ;
  assign q_no_rst = \dff_inst.q_no_rst ;
  assign q_syn_rst = \dff_inst.q_syn_rst ;
  assign \dff_inst.rst_n  = rst_n;
endmodule
