* SPICE netlist generated by Yosys 0.9+4274 (git sha1 e6dd4db0, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os)

X0 b c a sky130_fd_sc_hd__lpflow_inputiso1p_1

************************
* end of SPICE netlist *
************************

